/********************************************************************************
** Form generated from reading UI file 'editpitch.ui'
**
** Created by: Qt User Interface Compiler version 6.7.0
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef UI_EDITPITCH_H
#define UI_EDITPITCH_H

#include <QtCore/QVariant>
#include <QtWidgets/QAbstractButton>
#include <QtWidgets/QApplication>
#include <QtWidgets/QDialog>
#include <QtWidgets/QDialogButtonBox>
#include <QtWidgets/QHeaderView>
#include <QtWidgets/QLabel>
#include <QtWidgets/QTableWidget>
#include <QtWidgets/QVBoxLayout>

QT_BEGIN_NAMESPACE

class Ui_EditPitchBase
{
public:
    QVBoxLayout *verticalLayout;
    QLabel *label;
    QTableWidget *tableWidget;
    QDialogButtonBox *buttonBox;

    void setupUi(QDialog *EditPitchBase)
    {
        if (EditPitchBase->objectName().isEmpty())
            EditPitchBase->setObjectName("EditPitchBase");
        EditPitchBase->resize(735, 446);
        verticalLayout = new QVBoxLayout(EditPitchBase);
        verticalLayout->setObjectName("verticalLayout");
        label = new QLabel(EditPitchBase);
        label->setObjectName("label");

        verticalLayout->addWidget(label);

        tableWidget = new QTableWidget(EditPitchBase);
        if (tableWidget->columnCount() < 13)
            tableWidget->setColumnCount(13);
        QTableWidgetItem *__qtablewidgetitem = new QTableWidgetItem();
        tableWidget->setHorizontalHeaderItem(0, __qtablewidgetitem);
        QTableWidgetItem *__qtablewidgetitem1 = new QTableWidgetItem();
        tableWidget->setHorizontalHeaderItem(1, __qtablewidgetitem1);
        QTableWidgetItem *__qtablewidgetitem2 = new QTableWidgetItem();
        tableWidget->setHorizontalHeaderItem(2, __qtablewidgetitem2);
        QTableWidgetItem *__qtablewidgetitem3 = new QTableWidgetItem();
        tableWidget->setHorizontalHeaderItem(3, __qtablewidgetitem3);
        QTableWidgetItem *__qtablewidgetitem4 = new QTableWidgetItem();
        tableWidget->setHorizontalHeaderItem(4, __qtablewidgetitem4);
        QTableWidgetItem *__qtablewidgetitem5 = new QTableWidgetItem();
        tableWidget->setHorizontalHeaderItem(5, __qtablewidgetitem5);
        QTableWidgetItem *__qtablewidgetitem6 = new QTableWidgetItem();
        tableWidget->setHorizontalHeaderItem(6, __qtablewidgetitem6);
        QTableWidgetItem *__qtablewidgetitem7 = new QTableWidgetItem();
        tableWidget->setHorizontalHeaderItem(7, __qtablewidgetitem7);
        QTableWidgetItem *__qtablewidgetitem8 = new QTableWidgetItem();
        tableWidget->setHorizontalHeaderItem(8, __qtablewidgetitem8);
        QTableWidgetItem *__qtablewidgetitem9 = new QTableWidgetItem();
        tableWidget->setHorizontalHeaderItem(9, __qtablewidgetitem9);
        QTableWidgetItem *__qtablewidgetitem10 = new QTableWidgetItem();
        tableWidget->setHorizontalHeaderItem(10, __qtablewidgetitem10);
        QTableWidgetItem *__qtablewidgetitem11 = new QTableWidgetItem();
        tableWidget->setHorizontalHeaderItem(11, __qtablewidgetitem11);
        QTableWidgetItem *__qtablewidgetitem12 = new QTableWidgetItem();
        tableWidget->setHorizontalHeaderItem(12, __qtablewidgetitem12);
        if (tableWidget->rowCount() < 11)
            tableWidget->setRowCount(11);
        QTableWidgetItem *__qtablewidgetitem13 = new QTableWidgetItem();
        tableWidget->setVerticalHeaderItem(0, __qtablewidgetitem13);
        QTableWidgetItem *__qtablewidgetitem14 = new QTableWidgetItem();
        tableWidget->setVerticalHeaderItem(1, __qtablewidgetitem14);
        QTableWidgetItem *__qtablewidgetitem15 = new QTableWidgetItem();
        tableWidget->setVerticalHeaderItem(2, __qtablewidgetitem15);
        QTableWidgetItem *__qtablewidgetitem16 = new QTableWidgetItem();
        tableWidget->setVerticalHeaderItem(3, __qtablewidgetitem16);
        QTableWidgetItem *__qtablewidgetitem17 = new QTableWidgetItem();
        tableWidget->setVerticalHeaderItem(4, __qtablewidgetitem17);
        QTableWidgetItem *__qtablewidgetitem18 = new QTableWidgetItem();
        tableWidget->setVerticalHeaderItem(5, __qtablewidgetitem18);
        QTableWidgetItem *__qtablewidgetitem19 = new QTableWidgetItem();
        tableWidget->setVerticalHeaderItem(6, __qtablewidgetitem19);
        QTableWidgetItem *__qtablewidgetitem20 = new QTableWidgetItem();
        tableWidget->setVerticalHeaderItem(7, __qtablewidgetitem20);
        QTableWidgetItem *__qtablewidgetitem21 = new QTableWidgetItem();
        tableWidget->setVerticalHeaderItem(8, __qtablewidgetitem21);
        QTableWidgetItem *__qtablewidgetitem22 = new QTableWidgetItem();
        tableWidget->setVerticalHeaderItem(9, __qtablewidgetitem22);
        QTableWidgetItem *__qtablewidgetitem23 = new QTableWidgetItem();
        tableWidget->setVerticalHeaderItem(10, __qtablewidgetitem23);
        QTableWidgetItem *__qtablewidgetitem24 = new QTableWidgetItem();
        tableWidget->setItem(0, 0, __qtablewidgetitem24);
        QTableWidgetItem *__qtablewidgetitem25 = new QTableWidgetItem();
        tableWidget->setItem(0, 1, __qtablewidgetitem25);
        QTableWidgetItem *__qtablewidgetitem26 = new QTableWidgetItem();
        tableWidget->setItem(0, 2, __qtablewidgetitem26);
        QTableWidgetItem *__qtablewidgetitem27 = new QTableWidgetItem();
        tableWidget->setItem(0, 3, __qtablewidgetitem27);
        QTableWidgetItem *__qtablewidgetitem28 = new QTableWidgetItem();
        tableWidget->setItem(0, 4, __qtablewidgetitem28);
        QTableWidgetItem *__qtablewidgetitem29 = new QTableWidgetItem();
        tableWidget->setItem(0, 5, __qtablewidgetitem29);
        QTableWidgetItem *__qtablewidgetitem30 = new QTableWidgetItem();
        tableWidget->setItem(0, 6, __qtablewidgetitem30);
        QTableWidgetItem *__qtablewidgetitem31 = new QTableWidgetItem();
        tableWidget->setItem(0, 7, __qtablewidgetitem31);
        QTableWidgetItem *__qtablewidgetitem32 = new QTableWidgetItem();
        __qtablewidgetitem32->setFlags(Qt::NoItemFlags);
        tableWidget->setItem(0, 8, __qtablewidgetitem32);
        QTableWidgetItem *__qtablewidgetitem33 = new QTableWidgetItem();
        __qtablewidgetitem33->setFlags(Qt::NoItemFlags);
        tableWidget->setItem(0, 9, __qtablewidgetitem33);
        QTableWidgetItem *__qtablewidgetitem34 = new QTableWidgetItem();
        __qtablewidgetitem34->setFlags(Qt::NoItemFlags);
        tableWidget->setItem(0, 10, __qtablewidgetitem34);
        QTableWidgetItem *__qtablewidgetitem35 = new QTableWidgetItem();
        __qtablewidgetitem35->setFlags(Qt::NoItemFlags);
        tableWidget->setItem(0, 11, __qtablewidgetitem35);
        QTableWidgetItem *__qtablewidgetitem36 = new QTableWidgetItem();
        __qtablewidgetitem36->setFlags(Qt::NoItemFlags);
        tableWidget->setItem(0, 12, __qtablewidgetitem36);
        QFont font;
        font.setBold(true);
        QTableWidgetItem *__qtablewidgetitem37 = new QTableWidgetItem();
        __qtablewidgetitem37->setFont(font);
        __qtablewidgetitem37->setFlags(Qt::ItemIsSelectable|Qt::ItemIsEnabled);
        tableWidget->setItem(1, 0, __qtablewidgetitem37);
        QTableWidgetItem *__qtablewidgetitem38 = new QTableWidgetItem();
        __qtablewidgetitem38->setFlags(Qt::ItemIsSelectable|Qt::ItemIsEnabled);
        tableWidget->setItem(1, 1, __qtablewidgetitem38);
        QTableWidgetItem *__qtablewidgetitem39 = new QTableWidgetItem();
        __qtablewidgetitem39->setFlags(Qt::ItemIsSelectable|Qt::ItemIsEnabled);
        tableWidget->setItem(1, 2, __qtablewidgetitem39);
        QTableWidgetItem *__qtablewidgetitem40 = new QTableWidgetItem();
        __qtablewidgetitem40->setFlags(Qt::ItemIsSelectable|Qt::ItemIsEnabled);
        tableWidget->setItem(1, 3, __qtablewidgetitem40);
        QTableWidgetItem *__qtablewidgetitem41 = new QTableWidgetItem();
        __qtablewidgetitem41->setFlags(Qt::ItemIsSelectable|Qt::ItemIsEnabled);
        tableWidget->setItem(1, 4, __qtablewidgetitem41);
        QTableWidgetItem *__qtablewidgetitem42 = new QTableWidgetItem();
        __qtablewidgetitem42->setFlags(Qt::ItemIsSelectable|Qt::ItemIsEnabled);
        tableWidget->setItem(1, 5, __qtablewidgetitem42);
        QTableWidgetItem *__qtablewidgetitem43 = new QTableWidgetItem();
        __qtablewidgetitem43->setFlags(Qt::ItemIsSelectable|Qt::ItemIsEnabled);
        tableWidget->setItem(1, 6, __qtablewidgetitem43);
        QTableWidgetItem *__qtablewidgetitem44 = new QTableWidgetItem();
        __qtablewidgetitem44->setFlags(Qt::ItemIsSelectable|Qt::ItemIsEnabled);
        tableWidget->setItem(1, 7, __qtablewidgetitem44);
        QTableWidgetItem *__qtablewidgetitem45 = new QTableWidgetItem();
        __qtablewidgetitem45->setFlags(Qt::ItemIsSelectable|Qt::ItemIsEnabled);
        tableWidget->setItem(1, 8, __qtablewidgetitem45);
        QTableWidgetItem *__qtablewidgetitem46 = new QTableWidgetItem();
        __qtablewidgetitem46->setFlags(Qt::ItemIsSelectable|Qt::ItemIsEnabled);
        tableWidget->setItem(1, 9, __qtablewidgetitem46);
        QTableWidgetItem *__qtablewidgetitem47 = new QTableWidgetItem();
        __qtablewidgetitem47->setFlags(Qt::ItemIsSelectable|Qt::ItemIsEnabled);
        tableWidget->setItem(1, 10, __qtablewidgetitem47);
        QTableWidgetItem *__qtablewidgetitem48 = new QTableWidgetItem();
        __qtablewidgetitem48->setFlags(Qt::ItemIsSelectable|Qt::ItemIsEnabled);
        tableWidget->setItem(1, 11, __qtablewidgetitem48);
        QTableWidgetItem *__qtablewidgetitem49 = new QTableWidgetItem();
        __qtablewidgetitem49->setFlags(Qt::NoItemFlags);
        tableWidget->setItem(1, 12, __qtablewidgetitem49);
        QTableWidgetItem *__qtablewidgetitem50 = new QTableWidgetItem();
        __qtablewidgetitem50->setFont(font);
        __qtablewidgetitem50->setFlags(Qt::ItemIsSelectable|Qt::ItemIsEnabled);
        tableWidget->setItem(2, 0, __qtablewidgetitem50);
        QTableWidgetItem *__qtablewidgetitem51 = new QTableWidgetItem();
        __qtablewidgetitem51->setFlags(Qt::ItemIsSelectable|Qt::ItemIsEnabled);
        tableWidget->setItem(2, 1, __qtablewidgetitem51);
        QTableWidgetItem *__qtablewidgetitem52 = new QTableWidgetItem();
        __qtablewidgetitem52->setFlags(Qt::ItemIsSelectable|Qt::ItemIsEnabled);
        tableWidget->setItem(2, 2, __qtablewidgetitem52);
        QTableWidgetItem *__qtablewidgetitem53 = new QTableWidgetItem();
        __qtablewidgetitem53->setFlags(Qt::ItemIsSelectable|Qt::ItemIsEnabled);
        tableWidget->setItem(2, 3, __qtablewidgetitem53);
        QTableWidgetItem *__qtablewidgetitem54 = new QTableWidgetItem();
        __qtablewidgetitem54->setFlags(Qt::ItemIsSelectable|Qt::ItemIsEnabled);
        tableWidget->setItem(2, 4, __qtablewidgetitem54);
        QTableWidgetItem *__qtablewidgetitem55 = new QTableWidgetItem();
        __qtablewidgetitem55->setFlags(Qt::ItemIsSelectable|Qt::ItemIsEnabled);
        tableWidget->setItem(2, 5, __qtablewidgetitem55);
        QTableWidgetItem *__qtablewidgetitem56 = new QTableWidgetItem();
        __qtablewidgetitem56->setFlags(Qt::ItemIsSelectable|Qt::ItemIsEnabled);
        tableWidget->setItem(2, 6, __qtablewidgetitem56);
        QTableWidgetItem *__qtablewidgetitem57 = new QTableWidgetItem();
        __qtablewidgetitem57->setFlags(Qt::ItemIsSelectable|Qt::ItemIsEnabled);
        tableWidget->setItem(2, 7, __qtablewidgetitem57);
        QTableWidgetItem *__qtablewidgetitem58 = new QTableWidgetItem();
        __qtablewidgetitem58->setFlags(Qt::ItemIsSelectable|Qt::ItemIsEnabled);
        tableWidget->setItem(2, 8, __qtablewidgetitem58);
        QTableWidgetItem *__qtablewidgetitem59 = new QTableWidgetItem();
        __qtablewidgetitem59->setFlags(Qt::ItemIsSelectable|Qt::ItemIsEnabled);
        tableWidget->setItem(2, 9, __qtablewidgetitem59);
        QTableWidgetItem *__qtablewidgetitem60 = new QTableWidgetItem();
        __qtablewidgetitem60->setFlags(Qt::ItemIsSelectable|Qt::ItemIsEnabled);
        tableWidget->setItem(2, 10, __qtablewidgetitem60);
        QTableWidgetItem *__qtablewidgetitem61 = new QTableWidgetItem();
        __qtablewidgetitem61->setFlags(Qt::ItemIsSelectable|Qt::ItemIsEnabled);
        tableWidget->setItem(2, 11, __qtablewidgetitem61);
        QTableWidgetItem *__qtablewidgetitem62 = new QTableWidgetItem();
        __qtablewidgetitem62->setFlags(Qt::NoItemFlags);
        tableWidget->setItem(2, 12, __qtablewidgetitem62);
        QTableWidgetItem *__qtablewidgetitem63 = new QTableWidgetItem();
        __qtablewidgetitem63->setFont(font);
        __qtablewidgetitem63->setFlags(Qt::ItemIsSelectable|Qt::ItemIsEnabled);
        tableWidget->setItem(3, 0, __qtablewidgetitem63);
        QTableWidgetItem *__qtablewidgetitem64 = new QTableWidgetItem();
        __qtablewidgetitem64->setFlags(Qt::ItemIsSelectable|Qt::ItemIsEnabled);
        tableWidget->setItem(3, 1, __qtablewidgetitem64);
        QTableWidgetItem *__qtablewidgetitem65 = new QTableWidgetItem();
        __qtablewidgetitem65->setFlags(Qt::ItemIsSelectable|Qt::ItemIsEnabled);
        tableWidget->setItem(3, 2, __qtablewidgetitem65);
        QTableWidgetItem *__qtablewidgetitem66 = new QTableWidgetItem();
        __qtablewidgetitem66->setFlags(Qt::ItemIsSelectable|Qt::ItemIsEnabled);
        tableWidget->setItem(3, 3, __qtablewidgetitem66);
        QTableWidgetItem *__qtablewidgetitem67 = new QTableWidgetItem();
        __qtablewidgetitem67->setFlags(Qt::ItemIsSelectable|Qt::ItemIsEnabled);
        tableWidget->setItem(3, 4, __qtablewidgetitem67);
        QTableWidgetItem *__qtablewidgetitem68 = new QTableWidgetItem();
        __qtablewidgetitem68->setFlags(Qt::ItemIsSelectable|Qt::ItemIsEnabled);
        tableWidget->setItem(3, 5, __qtablewidgetitem68);
        QTableWidgetItem *__qtablewidgetitem69 = new QTableWidgetItem();
        __qtablewidgetitem69->setFlags(Qt::ItemIsSelectable|Qt::ItemIsEnabled);
        tableWidget->setItem(3, 6, __qtablewidgetitem69);
        QTableWidgetItem *__qtablewidgetitem70 = new QTableWidgetItem();
        __qtablewidgetitem70->setFlags(Qt::ItemIsSelectable|Qt::ItemIsEnabled);
        tableWidget->setItem(3, 7, __qtablewidgetitem70);
        QTableWidgetItem *__qtablewidgetitem71 = new QTableWidgetItem();
        __qtablewidgetitem71->setFlags(Qt::ItemIsSelectable|Qt::ItemIsEnabled);
        tableWidget->setItem(3, 8, __qtablewidgetitem71);
        QTableWidgetItem *__qtablewidgetitem72 = new QTableWidgetItem();
        __qtablewidgetitem72->setFlags(Qt::ItemIsSelectable|Qt::ItemIsEnabled);
        tableWidget->setItem(3, 9, __qtablewidgetitem72);
        QTableWidgetItem *__qtablewidgetitem73 = new QTableWidgetItem();
        __qtablewidgetitem73->setFlags(Qt::ItemIsSelectable|Qt::ItemIsEnabled);
        tableWidget->setItem(3, 10, __qtablewidgetitem73);
        QTableWidgetItem *__qtablewidgetitem74 = new QTableWidgetItem();
        __qtablewidgetitem74->setFlags(Qt::ItemIsSelectable|Qt::ItemIsEnabled);
        tableWidget->setItem(3, 11, __qtablewidgetitem74);
        QTableWidgetItem *__qtablewidgetitem75 = new QTableWidgetItem();
        __qtablewidgetitem75->setFlags(Qt::NoItemFlags);
        tableWidget->setItem(3, 12, __qtablewidgetitem75);
        QTableWidgetItem *__qtablewidgetitem76 = new QTableWidgetItem();
        __qtablewidgetitem76->setFont(font);
        __qtablewidgetitem76->setFlags(Qt::ItemIsSelectable|Qt::ItemIsEnabled);
        tableWidget->setItem(4, 0, __qtablewidgetitem76);
        QTableWidgetItem *__qtablewidgetitem77 = new QTableWidgetItem();
        __qtablewidgetitem77->setFlags(Qt::ItemIsSelectable|Qt::ItemIsEnabled);
        tableWidget->setItem(4, 1, __qtablewidgetitem77);
        QTableWidgetItem *__qtablewidgetitem78 = new QTableWidgetItem();
        __qtablewidgetitem78->setFlags(Qt::ItemIsSelectable|Qt::ItemIsEnabled);
        tableWidget->setItem(4, 2, __qtablewidgetitem78);
        QTableWidgetItem *__qtablewidgetitem79 = new QTableWidgetItem();
        __qtablewidgetitem79->setFlags(Qt::ItemIsSelectable|Qt::ItemIsEnabled);
        tableWidget->setItem(4, 3, __qtablewidgetitem79);
        QTableWidgetItem *__qtablewidgetitem80 = new QTableWidgetItem();
        __qtablewidgetitem80->setFlags(Qt::ItemIsSelectable|Qt::ItemIsEnabled);
        tableWidget->setItem(4, 4, __qtablewidgetitem80);
        QTableWidgetItem *__qtablewidgetitem81 = new QTableWidgetItem();
        __qtablewidgetitem81->setFlags(Qt::ItemIsSelectable|Qt::ItemIsEnabled);
        tableWidget->setItem(4, 5, __qtablewidgetitem81);
        QTableWidgetItem *__qtablewidgetitem82 = new QTableWidgetItem();
        __qtablewidgetitem82->setFlags(Qt::ItemIsSelectable|Qt::ItemIsEnabled);
        tableWidget->setItem(4, 6, __qtablewidgetitem82);
        QTableWidgetItem *__qtablewidgetitem83 = new QTableWidgetItem();
        __qtablewidgetitem83->setFlags(Qt::ItemIsSelectable|Qt::ItemIsEnabled);
        tableWidget->setItem(4, 7, __qtablewidgetitem83);
        QTableWidgetItem *__qtablewidgetitem84 = new QTableWidgetItem();
        __qtablewidgetitem84->setFlags(Qt::ItemIsSelectable|Qt::ItemIsEnabled);
        tableWidget->setItem(4, 8, __qtablewidgetitem84);
        QTableWidgetItem *__qtablewidgetitem85 = new QTableWidgetItem();
        __qtablewidgetitem85->setFlags(Qt::ItemIsSelectable|Qt::ItemIsEnabled);
        tableWidget->setItem(4, 9, __qtablewidgetitem85);
        QTableWidgetItem *__qtablewidgetitem86 = new QTableWidgetItem();
        __qtablewidgetitem86->setFlags(Qt::ItemIsSelectable|Qt::ItemIsEnabled);
        tableWidget->setItem(4, 10, __qtablewidgetitem86);
        QTableWidgetItem *__qtablewidgetitem87 = new QTableWidgetItem();
        __qtablewidgetitem87->setFlags(Qt::ItemIsSelectable|Qt::ItemIsEnabled);
        tableWidget->setItem(4, 11, __qtablewidgetitem87);
        QTableWidgetItem *__qtablewidgetitem88 = new QTableWidgetItem();
        __qtablewidgetitem88->setFlags(Qt::NoItemFlags);
        tableWidget->setItem(4, 12, __qtablewidgetitem88);
        QTableWidgetItem *__qtablewidgetitem89 = new QTableWidgetItem();
        __qtablewidgetitem89->setFont(font);
        __qtablewidgetitem89->setFlags(Qt::ItemIsSelectable|Qt::ItemIsEnabled);
        tableWidget->setItem(5, 0, __qtablewidgetitem89);
        QTableWidgetItem *__qtablewidgetitem90 = new QTableWidgetItem();
        __qtablewidgetitem90->setFlags(Qt::ItemIsSelectable|Qt::ItemIsEnabled);
        tableWidget->setItem(5, 1, __qtablewidgetitem90);
        QTableWidgetItem *__qtablewidgetitem91 = new QTableWidgetItem();
        __qtablewidgetitem91->setFlags(Qt::ItemIsSelectable|Qt::ItemIsEnabled);
        tableWidget->setItem(5, 2, __qtablewidgetitem91);
        QTableWidgetItem *__qtablewidgetitem92 = new QTableWidgetItem();
        __qtablewidgetitem92->setFlags(Qt::ItemIsSelectable|Qt::ItemIsEnabled);
        tableWidget->setItem(5, 3, __qtablewidgetitem92);
        QTableWidgetItem *__qtablewidgetitem93 = new QTableWidgetItem();
        __qtablewidgetitem93->setFlags(Qt::ItemIsSelectable|Qt::ItemIsEnabled);
        tableWidget->setItem(5, 4, __qtablewidgetitem93);
        QTableWidgetItem *__qtablewidgetitem94 = new QTableWidgetItem();
        __qtablewidgetitem94->setFlags(Qt::ItemIsSelectable|Qt::ItemIsEnabled);
        tableWidget->setItem(5, 5, __qtablewidgetitem94);
        QTableWidgetItem *__qtablewidgetitem95 = new QTableWidgetItem();
        __qtablewidgetitem95->setFlags(Qt::ItemIsSelectable|Qt::ItemIsEnabled);
        tableWidget->setItem(5, 6, __qtablewidgetitem95);
        QTableWidgetItem *__qtablewidgetitem96 = new QTableWidgetItem();
        __qtablewidgetitem96->setFlags(Qt::ItemIsSelectable|Qt::ItemIsEnabled);
        tableWidget->setItem(5, 7, __qtablewidgetitem96);
        QTableWidgetItem *__qtablewidgetitem97 = new QTableWidgetItem();
        __qtablewidgetitem97->setFlags(Qt::ItemIsSelectable|Qt::ItemIsEnabled);
        tableWidget->setItem(5, 8, __qtablewidgetitem97);
        QTableWidgetItem *__qtablewidgetitem98 = new QTableWidgetItem();
        __qtablewidgetitem98->setFlags(Qt::ItemIsSelectable|Qt::ItemIsEnabled);
        tableWidget->setItem(5, 9, __qtablewidgetitem98);
        QTableWidgetItem *__qtablewidgetitem99 = new QTableWidgetItem();
        __qtablewidgetitem99->setFlags(Qt::ItemIsSelectable|Qt::ItemIsEnabled);
        tableWidget->setItem(5, 10, __qtablewidgetitem99);
        QTableWidgetItem *__qtablewidgetitem100 = new QTableWidgetItem();
        __qtablewidgetitem100->setFlags(Qt::ItemIsSelectable|Qt::ItemIsEnabled);
        tableWidget->setItem(5, 11, __qtablewidgetitem100);
        QTableWidgetItem *__qtablewidgetitem101 = new QTableWidgetItem();
        __qtablewidgetitem101->setFlags(Qt::NoItemFlags);
        tableWidget->setItem(5, 12, __qtablewidgetitem101);
        QTableWidgetItem *__qtablewidgetitem102 = new QTableWidgetItem();
        __qtablewidgetitem102->setFont(font);
        __qtablewidgetitem102->setFlags(Qt::ItemIsSelectable|Qt::ItemIsEnabled);
        tableWidget->setItem(6, 0, __qtablewidgetitem102);
        QTableWidgetItem *__qtablewidgetitem103 = new QTableWidgetItem();
        __qtablewidgetitem103->setFlags(Qt::ItemIsSelectable|Qt::ItemIsEnabled);
        tableWidget->setItem(6, 1, __qtablewidgetitem103);
        QTableWidgetItem *__qtablewidgetitem104 = new QTableWidgetItem();
        __qtablewidgetitem104->setFlags(Qt::ItemIsSelectable|Qt::ItemIsEnabled);
        tableWidget->setItem(6, 2, __qtablewidgetitem104);
        QTableWidgetItem *__qtablewidgetitem105 = new QTableWidgetItem();
        __qtablewidgetitem105->setFlags(Qt::ItemIsSelectable|Qt::ItemIsEnabled);
        tableWidget->setItem(6, 3, __qtablewidgetitem105);
        QTableWidgetItem *__qtablewidgetitem106 = new QTableWidgetItem();
        __qtablewidgetitem106->setFlags(Qt::ItemIsSelectable|Qt::ItemIsEnabled);
        tableWidget->setItem(6, 4, __qtablewidgetitem106);
        QTableWidgetItem *__qtablewidgetitem107 = new QTableWidgetItem();
        __qtablewidgetitem107->setFlags(Qt::ItemIsSelectable|Qt::ItemIsEnabled);
        tableWidget->setItem(6, 5, __qtablewidgetitem107);
        QTableWidgetItem *__qtablewidgetitem108 = new QTableWidgetItem();
        __qtablewidgetitem108->setFlags(Qt::ItemIsSelectable|Qt::ItemIsEnabled);
        tableWidget->setItem(6, 6, __qtablewidgetitem108);
        QTableWidgetItem *__qtablewidgetitem109 = new QTableWidgetItem();
        __qtablewidgetitem109->setFlags(Qt::ItemIsSelectable|Qt::ItemIsEnabled);
        tableWidget->setItem(6, 7, __qtablewidgetitem109);
        QTableWidgetItem *__qtablewidgetitem110 = new QTableWidgetItem();
        __qtablewidgetitem110->setFlags(Qt::ItemIsSelectable|Qt::ItemIsEnabled);
        tableWidget->setItem(6, 8, __qtablewidgetitem110);
        QTableWidgetItem *__qtablewidgetitem111 = new QTableWidgetItem();
        __qtablewidgetitem111->setFlags(Qt::ItemIsSelectable|Qt::ItemIsEnabled);
        tableWidget->setItem(6, 9, __qtablewidgetitem111);
        QTableWidgetItem *__qtablewidgetitem112 = new QTableWidgetItem();
        __qtablewidgetitem112->setFlags(Qt::ItemIsSelectable|Qt::ItemIsEnabled);
        tableWidget->setItem(6, 10, __qtablewidgetitem112);
        QTableWidgetItem *__qtablewidgetitem113 = new QTableWidgetItem();
        __qtablewidgetitem113->setFlags(Qt::ItemIsSelectable|Qt::ItemIsEnabled);
        tableWidget->setItem(6, 11, __qtablewidgetitem113);
        QTableWidgetItem *__qtablewidgetitem114 = new QTableWidgetItem();
        __qtablewidgetitem114->setFlags(Qt::NoItemFlags);
        tableWidget->setItem(6, 12, __qtablewidgetitem114);
        QTableWidgetItem *__qtablewidgetitem115 = new QTableWidgetItem();
        __qtablewidgetitem115->setFont(font);
        __qtablewidgetitem115->setFlags(Qt::ItemIsSelectable|Qt::ItemIsEnabled);
        tableWidget->setItem(7, 0, __qtablewidgetitem115);
        QTableWidgetItem *__qtablewidgetitem116 = new QTableWidgetItem();
        __qtablewidgetitem116->setFlags(Qt::ItemIsSelectable|Qt::ItemIsEnabled);
        tableWidget->setItem(7, 1, __qtablewidgetitem116);
        QTableWidgetItem *__qtablewidgetitem117 = new QTableWidgetItem();
        __qtablewidgetitem117->setFlags(Qt::ItemIsSelectable|Qt::ItemIsEnabled);
        tableWidget->setItem(7, 2, __qtablewidgetitem117);
        QTableWidgetItem *__qtablewidgetitem118 = new QTableWidgetItem();
        __qtablewidgetitem118->setFlags(Qt::ItemIsSelectable|Qt::ItemIsEnabled);
        tableWidget->setItem(7, 3, __qtablewidgetitem118);
        QTableWidgetItem *__qtablewidgetitem119 = new QTableWidgetItem();
        __qtablewidgetitem119->setFlags(Qt::ItemIsSelectable|Qt::ItemIsEnabled);
        tableWidget->setItem(7, 4, __qtablewidgetitem119);
        QTableWidgetItem *__qtablewidgetitem120 = new QTableWidgetItem();
        __qtablewidgetitem120->setFlags(Qt::ItemIsSelectable|Qt::ItemIsEnabled);
        tableWidget->setItem(7, 5, __qtablewidgetitem120);
        QTableWidgetItem *__qtablewidgetitem121 = new QTableWidgetItem();
        __qtablewidgetitem121->setFlags(Qt::ItemIsSelectable|Qt::ItemIsEnabled);
        tableWidget->setItem(7, 6, __qtablewidgetitem121);
        QTableWidgetItem *__qtablewidgetitem122 = new QTableWidgetItem();
        __qtablewidgetitem122->setFlags(Qt::ItemIsSelectable|Qt::ItemIsEnabled);
        tableWidget->setItem(7, 7, __qtablewidgetitem122);
        QTableWidgetItem *__qtablewidgetitem123 = new QTableWidgetItem();
        __qtablewidgetitem123->setFlags(Qt::ItemIsSelectable|Qt::ItemIsEnabled);
        tableWidget->setItem(7, 8, __qtablewidgetitem123);
        QTableWidgetItem *__qtablewidgetitem124 = new QTableWidgetItem();
        __qtablewidgetitem124->setFlags(Qt::ItemIsSelectable|Qt::ItemIsEnabled);
        tableWidget->setItem(7, 9, __qtablewidgetitem124);
        QTableWidgetItem *__qtablewidgetitem125 = new QTableWidgetItem();
        __qtablewidgetitem125->setFlags(Qt::ItemIsSelectable|Qt::ItemIsEnabled);
        tableWidget->setItem(7, 10, __qtablewidgetitem125);
        QTableWidgetItem *__qtablewidgetitem126 = new QTableWidgetItem();
        __qtablewidgetitem126->setFlags(Qt::ItemIsSelectable|Qt::ItemIsEnabled);
        tableWidget->setItem(7, 11, __qtablewidgetitem126);
        QTableWidgetItem *__qtablewidgetitem127 = new QTableWidgetItem();
        __qtablewidgetitem127->setFlags(Qt::NoItemFlags);
        tableWidget->setItem(7, 12, __qtablewidgetitem127);
        QTableWidgetItem *__qtablewidgetitem128 = new QTableWidgetItem();
        __qtablewidgetitem128->setFont(font);
        __qtablewidgetitem128->setFlags(Qt::ItemIsSelectable|Qt::ItemIsEnabled);
        tableWidget->setItem(8, 0, __qtablewidgetitem128);
        QTableWidgetItem *__qtablewidgetitem129 = new QTableWidgetItem();
        __qtablewidgetitem129->setFlags(Qt::ItemIsSelectable|Qt::ItemIsEnabled);
        tableWidget->setItem(8, 1, __qtablewidgetitem129);
        QTableWidgetItem *__qtablewidgetitem130 = new QTableWidgetItem();
        __qtablewidgetitem130->setFlags(Qt::ItemIsSelectable|Qt::ItemIsEnabled);
        tableWidget->setItem(8, 2, __qtablewidgetitem130);
        QTableWidgetItem *__qtablewidgetitem131 = new QTableWidgetItem();
        __qtablewidgetitem131->setFlags(Qt::ItemIsSelectable|Qt::ItemIsEnabled);
        tableWidget->setItem(8, 3, __qtablewidgetitem131);
        QTableWidgetItem *__qtablewidgetitem132 = new QTableWidgetItem();
        __qtablewidgetitem132->setFlags(Qt::ItemIsSelectable|Qt::ItemIsEnabled);
        tableWidget->setItem(8, 4, __qtablewidgetitem132);
        QTableWidgetItem *__qtablewidgetitem133 = new QTableWidgetItem();
        __qtablewidgetitem133->setFlags(Qt::ItemIsSelectable|Qt::ItemIsEnabled);
        tableWidget->setItem(8, 5, __qtablewidgetitem133);
        QTableWidgetItem *__qtablewidgetitem134 = new QTableWidgetItem();
        __qtablewidgetitem134->setFlags(Qt::ItemIsSelectable|Qt::ItemIsEnabled);
        tableWidget->setItem(8, 6, __qtablewidgetitem134);
        QTableWidgetItem *__qtablewidgetitem135 = new QTableWidgetItem();
        __qtablewidgetitem135->setFlags(Qt::ItemIsSelectable|Qt::ItemIsEnabled);
        tableWidget->setItem(8, 7, __qtablewidgetitem135);
        QTableWidgetItem *__qtablewidgetitem136 = new QTableWidgetItem();
        __qtablewidgetitem136->setFlags(Qt::ItemIsSelectable|Qt::ItemIsEnabled);
        tableWidget->setItem(8, 8, __qtablewidgetitem136);
        QTableWidgetItem *__qtablewidgetitem137 = new QTableWidgetItem();
        __qtablewidgetitem137->setFlags(Qt::ItemIsSelectable|Qt::ItemIsEnabled);
        tableWidget->setItem(8, 9, __qtablewidgetitem137);
        QTableWidgetItem *__qtablewidgetitem138 = new QTableWidgetItem();
        __qtablewidgetitem138->setFlags(Qt::ItemIsSelectable|Qt::ItemIsEnabled);
        tableWidget->setItem(8, 10, __qtablewidgetitem138);
        QTableWidgetItem *__qtablewidgetitem139 = new QTableWidgetItem();
        __qtablewidgetitem139->setFlags(Qt::ItemIsSelectable|Qt::ItemIsEnabled);
        tableWidget->setItem(8, 11, __qtablewidgetitem139);
        QTableWidgetItem *__qtablewidgetitem140 = new QTableWidgetItem();
        __qtablewidgetitem140->setFlags(Qt::NoItemFlags);
        tableWidget->setItem(8, 12, __qtablewidgetitem140);
        QTableWidgetItem *__qtablewidgetitem141 = new QTableWidgetItem();
        __qtablewidgetitem141->setFont(font);
        __qtablewidgetitem141->setFlags(Qt::ItemIsSelectable|Qt::ItemIsEnabled);
        tableWidget->setItem(9, 0, __qtablewidgetitem141);
        QTableWidgetItem *__qtablewidgetitem142 = new QTableWidgetItem();
        __qtablewidgetitem142->setFlags(Qt::ItemIsSelectable|Qt::ItemIsEnabled);
        tableWidget->setItem(9, 1, __qtablewidgetitem142);
        QTableWidgetItem *__qtablewidgetitem143 = new QTableWidgetItem();
        __qtablewidgetitem143->setFlags(Qt::ItemIsSelectable|Qt::ItemIsEnabled);
        tableWidget->setItem(9, 2, __qtablewidgetitem143);
        QTableWidgetItem *__qtablewidgetitem144 = new QTableWidgetItem();
        __qtablewidgetitem144->setFlags(Qt::ItemIsSelectable|Qt::ItemIsEnabled);
        tableWidget->setItem(9, 3, __qtablewidgetitem144);
        QTableWidgetItem *__qtablewidgetitem145 = new QTableWidgetItem();
        __qtablewidgetitem145->setFlags(Qt::ItemIsSelectable|Qt::ItemIsEnabled);
        tableWidget->setItem(9, 4, __qtablewidgetitem145);
        QTableWidgetItem *__qtablewidgetitem146 = new QTableWidgetItem();
        __qtablewidgetitem146->setFlags(Qt::ItemIsSelectable|Qt::ItemIsEnabled);
        tableWidget->setItem(9, 5, __qtablewidgetitem146);
        QTableWidgetItem *__qtablewidgetitem147 = new QTableWidgetItem();
        __qtablewidgetitem147->setFlags(Qt::ItemIsSelectable|Qt::ItemIsEnabled);
        tableWidget->setItem(9, 6, __qtablewidgetitem147);
        QTableWidgetItem *__qtablewidgetitem148 = new QTableWidgetItem();
        __qtablewidgetitem148->setFlags(Qt::ItemIsSelectable|Qt::ItemIsEnabled);
        tableWidget->setItem(9, 7, __qtablewidgetitem148);
        QTableWidgetItem *__qtablewidgetitem149 = new QTableWidgetItem();
        __qtablewidgetitem149->setFlags(Qt::ItemIsSelectable|Qt::ItemIsEnabled);
        tableWidget->setItem(9, 8, __qtablewidgetitem149);
        QTableWidgetItem *__qtablewidgetitem150 = new QTableWidgetItem();
        __qtablewidgetitem150->setFlags(Qt::ItemIsSelectable|Qt::ItemIsEnabled);
        tableWidget->setItem(9, 9, __qtablewidgetitem150);
        QTableWidgetItem *__qtablewidgetitem151 = new QTableWidgetItem();
        __qtablewidgetitem151->setFlags(Qt::ItemIsSelectable|Qt::ItemIsEnabled);
        tableWidget->setItem(9, 10, __qtablewidgetitem151);
        QTableWidgetItem *__qtablewidgetitem152 = new QTableWidgetItem();
        __qtablewidgetitem152->setFlags(Qt::ItemIsSelectable|Qt::ItemIsEnabled);
        tableWidget->setItem(9, 11, __qtablewidgetitem152);
        QTableWidgetItem *__qtablewidgetitem153 = new QTableWidgetItem();
        __qtablewidgetitem153->setFlags(Qt::NoItemFlags);
        tableWidget->setItem(9, 12, __qtablewidgetitem153);
        QTableWidgetItem *__qtablewidgetitem154 = new QTableWidgetItem();
        __qtablewidgetitem154->setFont(font);
        __qtablewidgetitem154->setFlags(Qt::ItemIsSelectable|Qt::ItemIsEnabled);
        tableWidget->setItem(10, 0, __qtablewidgetitem154);
        QTableWidgetItem *__qtablewidgetitem155 = new QTableWidgetItem();
        __qtablewidgetitem155->setFlags(Qt::ItemIsSelectable|Qt::ItemIsEnabled);
        tableWidget->setItem(10, 1, __qtablewidgetitem155);
        QTableWidgetItem *__qtablewidgetitem156 = new QTableWidgetItem();
        __qtablewidgetitem156->setFlags(Qt::ItemIsSelectable|Qt::ItemIsEnabled);
        tableWidget->setItem(10, 2, __qtablewidgetitem156);
        QTableWidgetItem *__qtablewidgetitem157 = new QTableWidgetItem();
        __qtablewidgetitem157->setFlags(Qt::ItemIsSelectable|Qt::ItemIsEnabled);
        tableWidget->setItem(10, 3, __qtablewidgetitem157);
        QTableWidgetItem *__qtablewidgetitem158 = new QTableWidgetItem();
        __qtablewidgetitem158->setFlags(Qt::ItemIsSelectable|Qt::ItemIsEnabled);
        tableWidget->setItem(10, 4, __qtablewidgetitem158);
        QTableWidgetItem *__qtablewidgetitem159 = new QTableWidgetItem();
        __qtablewidgetitem159->setFlags(Qt::ItemIsSelectable|Qt::ItemIsEnabled);
        tableWidget->setItem(10, 5, __qtablewidgetitem159);
        QTableWidgetItem *__qtablewidgetitem160 = new QTableWidgetItem();
        __qtablewidgetitem160->setFlags(Qt::ItemIsSelectable|Qt::ItemIsEnabled);
        tableWidget->setItem(10, 6, __qtablewidgetitem160);
        QTableWidgetItem *__qtablewidgetitem161 = new QTableWidgetItem();
        __qtablewidgetitem161->setFlags(Qt::ItemIsSelectable|Qt::ItemIsEnabled);
        tableWidget->setItem(10, 7, __qtablewidgetitem161);
        QTableWidgetItem *__qtablewidgetitem162 = new QTableWidgetItem();
        __qtablewidgetitem162->setFlags(Qt::ItemIsSelectable|Qt::ItemIsEnabled);
        tableWidget->setItem(10, 8, __qtablewidgetitem162);
        QTableWidgetItem *__qtablewidgetitem163 = new QTableWidgetItem();
        __qtablewidgetitem163->setFlags(Qt::ItemIsSelectable|Qt::ItemIsEnabled);
        tableWidget->setItem(10, 9, __qtablewidgetitem163);
        QTableWidgetItem *__qtablewidgetitem164 = new QTableWidgetItem();
        __qtablewidgetitem164->setFlags(Qt::ItemIsSelectable|Qt::ItemIsEnabled);
        tableWidget->setItem(10, 10, __qtablewidgetitem164);
        QTableWidgetItem *__qtablewidgetitem165 = new QTableWidgetItem();
        __qtablewidgetitem165->setFlags(Qt::ItemIsSelectable|Qt::ItemIsEnabled);
        tableWidget->setItem(10, 11, __qtablewidgetitem165);
        QTableWidgetItem *__qtablewidgetitem166 = new QTableWidgetItem();
        __qtablewidgetitem166->setFlags(Qt::NoItemFlags);
        tableWidget->setItem(10, 12, __qtablewidgetitem166);
        tableWidget->setObjectName("tableWidget");
        QFont font1;
        font1.setPointSize(8);
        tableWidget->setFont(font1);
        tableWidget->setEditTriggers(QAbstractItemView::DoubleClicked);
        tableWidget->setDragDropOverwriteMode(false);
        tableWidget->setSelectionMode(QAbstractItemView::SingleSelection);
        tableWidget->setRowCount(11);
        tableWidget->setColumnCount(13);
        tableWidget->horizontalHeader()->setMinimumSectionSize(20);
        tableWidget->horizontalHeader()->setDefaultSectionSize(50);
        tableWidget->verticalHeader()->setDefaultSectionSize(32);

        verticalLayout->addWidget(tableWidget);

        buttonBox = new QDialogButtonBox(EditPitchBase);
        buttonBox->setObjectName("buttonBox");
        buttonBox->setOrientation(Qt::Horizontal);
        buttonBox->setStandardButtons(QDialogButtonBox::Cancel|QDialogButtonBox::Ok);

        verticalLayout->addWidget(buttonBox);


        retranslateUi(EditPitchBase);
        QObject::connect(buttonBox, &QDialogButtonBox::accepted, EditPitchBase, qOverload<>(&QDialog::accept));
        QObject::connect(buttonBox, &QDialogButtonBox::rejected, EditPitchBase, qOverload<>(&QDialog::reject));

        QMetaObject::connectSlotsByName(EditPitchBase);
    } // setupUi

    void retranslateUi(QDialog *EditPitchBase)
    {
        EditPitchBase->setWindowTitle(QCoreApplication::translate("EditPitchBase", "Note selection", nullptr));
        label->setText(QCoreApplication::translate("EditPitchBase", "Select note:", nullptr));
        QTableWidgetItem *___qtablewidgetitem = tableWidget->horizontalHeaderItem(0);
        ___qtablewidgetitem->setText(QCoreApplication::translate("EditPitchBase", "C", nullptr));
        QTableWidgetItem *___qtablewidgetitem1 = tableWidget->horizontalHeaderItem(1);
        ___qtablewidgetitem1->setText(QCoreApplication::translate("EditPitchBase", "C\342\231\257", nullptr));
        QTableWidgetItem *___qtablewidgetitem2 = tableWidget->horizontalHeaderItem(2);
        ___qtablewidgetitem2->setText(QCoreApplication::translate("EditPitchBase", "D", nullptr));
        QTableWidgetItem *___qtablewidgetitem3 = tableWidget->horizontalHeaderItem(3);
        ___qtablewidgetitem3->setText(QCoreApplication::translate("EditPitchBase", "E\342\231\255", nullptr));
        QTableWidgetItem *___qtablewidgetitem4 = tableWidget->horizontalHeaderItem(4);
        ___qtablewidgetitem4->setText(QCoreApplication::translate("EditPitchBase", "E", nullptr));
        QTableWidgetItem *___qtablewidgetitem5 = tableWidget->horizontalHeaderItem(5);
        ___qtablewidgetitem5->setText(QCoreApplication::translate("EditPitchBase", "F", nullptr));
        QTableWidgetItem *___qtablewidgetitem6 = tableWidget->horizontalHeaderItem(6);
        ___qtablewidgetitem6->setText(QCoreApplication::translate("EditPitchBase", "F\342\231\257", nullptr));
        QTableWidgetItem *___qtablewidgetitem7 = tableWidget->horizontalHeaderItem(7);
        ___qtablewidgetitem7->setText(QCoreApplication::translate("EditPitchBase", "G", nullptr));
        QTableWidgetItem *___qtablewidgetitem8 = tableWidget->horizontalHeaderItem(8);
        ___qtablewidgetitem8->setText(QCoreApplication::translate("EditPitchBase", "A\342\231\255", nullptr));
        QTableWidgetItem *___qtablewidgetitem9 = tableWidget->horizontalHeaderItem(9);
        ___qtablewidgetitem9->setText(QCoreApplication::translate("EditPitchBase", "A", nullptr));
        QTableWidgetItem *___qtablewidgetitem10 = tableWidget->horizontalHeaderItem(10);
        ___qtablewidgetitem10->setText(QCoreApplication::translate("EditPitchBase", "B\342\231\255", nullptr));
        QTableWidgetItem *___qtablewidgetitem11 = tableWidget->horizontalHeaderItem(11);
        ___qtablewidgetitem11->setText(QCoreApplication::translate("EditPitchBase", "B", nullptr));
        QTableWidgetItem *___qtablewidgetitem12 = tableWidget->horizontalHeaderItem(12);
        ___qtablewidgetitem12->setText(QCoreApplication::translate("EditPitchBase", "\302\273C", nullptr));
        QTableWidgetItem *___qtablewidgetitem13 = tableWidget->verticalHeaderItem(0);
        ___qtablewidgetitem13->setText(QCoreApplication::translate("EditPitchBase", "Octave 9", nullptr));
        QTableWidgetItem *___qtablewidgetitem14 = tableWidget->verticalHeaderItem(1);
        ___qtablewidgetitem14->setText(QCoreApplication::translate("EditPitchBase", "Octave 8", nullptr));
        QTableWidgetItem *___qtablewidgetitem15 = tableWidget->verticalHeaderItem(2);
        ___qtablewidgetitem15->setText(QCoreApplication::translate("EditPitchBase", "Octave 7", nullptr));
        QTableWidgetItem *___qtablewidgetitem16 = tableWidget->verticalHeaderItem(3);
        ___qtablewidgetitem16->setText(QCoreApplication::translate("EditPitchBase", "Octave 6", nullptr));
        QTableWidgetItem *___qtablewidgetitem17 = tableWidget->verticalHeaderItem(4);
        ___qtablewidgetitem17->setText(QCoreApplication::translate("EditPitchBase", "Octave 5", nullptr));
        QTableWidgetItem *___qtablewidgetitem18 = tableWidget->verticalHeaderItem(5);
        ___qtablewidgetitem18->setText(QCoreApplication::translate("EditPitchBase", "Octave 4", nullptr));
        QTableWidgetItem *___qtablewidgetitem19 = tableWidget->verticalHeaderItem(6);
        ___qtablewidgetitem19->setText(QCoreApplication::translate("EditPitchBase", "Octave 3", nullptr));
        QTableWidgetItem *___qtablewidgetitem20 = tableWidget->verticalHeaderItem(7);
        ___qtablewidgetitem20->setText(QCoreApplication::translate("EditPitchBase", "Octave 2", nullptr));
        QTableWidgetItem *___qtablewidgetitem21 = tableWidget->verticalHeaderItem(8);
        ___qtablewidgetitem21->setText(QCoreApplication::translate("EditPitchBase", "Octave 1", nullptr));
        QTableWidgetItem *___qtablewidgetitem22 = tableWidget->verticalHeaderItem(9);
        ___qtablewidgetitem22->setText(QCoreApplication::translate("EditPitchBase", "Octave 0", nullptr));
        QTableWidgetItem *___qtablewidgetitem23 = tableWidget->verticalHeaderItem(10);
        ___qtablewidgetitem23->setText(QCoreApplication::translate("EditPitchBase", "Octave -1", nullptr));

        const bool __sortingEnabled = tableWidget->isSortingEnabled();
        tableWidget->setSortingEnabled(false);
        QTableWidgetItem *___qtablewidgetitem24 = tableWidget->item(0, 0);
        ___qtablewidgetitem24->setText(QCoreApplication::translate("EditPitchBase", "C 9", nullptr));
        QTableWidgetItem *___qtablewidgetitem25 = tableWidget->item(0, 1);
        ___qtablewidgetitem25->setText(QCoreApplication::translate("EditPitchBase", "C\342\231\257 9", nullptr));
        QTableWidgetItem *___qtablewidgetitem26 = tableWidget->item(0, 2);
        ___qtablewidgetitem26->setText(QCoreApplication::translate("EditPitchBase", "D 9", nullptr));
        QTableWidgetItem *___qtablewidgetitem27 = tableWidget->item(0, 3);
        ___qtablewidgetitem27->setText(QCoreApplication::translate("EditPitchBase", "E\342\231\255 9", nullptr));
        QTableWidgetItem *___qtablewidgetitem28 = tableWidget->item(0, 4);
        ___qtablewidgetitem28->setText(QCoreApplication::translate("EditPitchBase", "E 9", nullptr));
        QTableWidgetItem *___qtablewidgetitem29 = tableWidget->item(0, 5);
        ___qtablewidgetitem29->setText(QCoreApplication::translate("EditPitchBase", "F 9", nullptr));
        QTableWidgetItem *___qtablewidgetitem30 = tableWidget->item(0, 6);
        ___qtablewidgetitem30->setText(QCoreApplication::translate("EditPitchBase", "F\342\231\257 9", nullptr));
        QTableWidgetItem *___qtablewidgetitem31 = tableWidget->item(0, 7);
        ___qtablewidgetitem31->setText(QCoreApplication::translate("EditPitchBase", "G 9", nullptr));
        QTableWidgetItem *___qtablewidgetitem32 = tableWidget->item(1, 0);
        ___qtablewidgetitem32->setText(QCoreApplication::translate("EditPitchBase", "C 8", nullptr));
        QTableWidgetItem *___qtablewidgetitem33 = tableWidget->item(1, 1);
        ___qtablewidgetitem33->setText(QCoreApplication::translate("EditPitchBase", "C\342\231\257 8", nullptr));
        QTableWidgetItem *___qtablewidgetitem34 = tableWidget->item(1, 2);
        ___qtablewidgetitem34->setText(QCoreApplication::translate("EditPitchBase", "D 8", nullptr));
        QTableWidgetItem *___qtablewidgetitem35 = tableWidget->item(1, 3);
        ___qtablewidgetitem35->setText(QCoreApplication::translate("EditPitchBase", "E\342\231\255 8", nullptr));
        QTableWidgetItem *___qtablewidgetitem36 = tableWidget->item(1, 4);
        ___qtablewidgetitem36->setText(QCoreApplication::translate("EditPitchBase", "E 8", nullptr));
        QTableWidgetItem *___qtablewidgetitem37 = tableWidget->item(1, 5);
        ___qtablewidgetitem37->setText(QCoreApplication::translate("EditPitchBase", "F 8", nullptr));
        QTableWidgetItem *___qtablewidgetitem38 = tableWidget->item(1, 6);
        ___qtablewidgetitem38->setText(QCoreApplication::translate("EditPitchBase", "F\342\231\257 8", nullptr));
        QTableWidgetItem *___qtablewidgetitem39 = tableWidget->item(1, 7);
        ___qtablewidgetitem39->setText(QCoreApplication::translate("EditPitchBase", "G 8", nullptr));
        QTableWidgetItem *___qtablewidgetitem40 = tableWidget->item(1, 8);
        ___qtablewidgetitem40->setText(QCoreApplication::translate("EditPitchBase", "A\342\231\255 8", nullptr));
        QTableWidgetItem *___qtablewidgetitem41 = tableWidget->item(1, 9);
        ___qtablewidgetitem41->setText(QCoreApplication::translate("EditPitchBase", "A 8", nullptr));
        QTableWidgetItem *___qtablewidgetitem42 = tableWidget->item(1, 10);
        ___qtablewidgetitem42->setText(QCoreApplication::translate("EditPitchBase", "B\342\231\255 8", nullptr));
        QTableWidgetItem *___qtablewidgetitem43 = tableWidget->item(1, 11);
        ___qtablewidgetitem43->setText(QCoreApplication::translate("EditPitchBase", "B 8", nullptr));
        QTableWidgetItem *___qtablewidgetitem44 = tableWidget->item(1, 12);
        ___qtablewidgetitem44->setText(QCoreApplication::translate("EditPitchBase", "C 9", nullptr));
        QTableWidgetItem *___qtablewidgetitem45 = tableWidget->item(2, 0);
        ___qtablewidgetitem45->setText(QCoreApplication::translate("EditPitchBase", "C 7", nullptr));
        QTableWidgetItem *___qtablewidgetitem46 = tableWidget->item(2, 1);
        ___qtablewidgetitem46->setText(QCoreApplication::translate("EditPitchBase", "C\342\231\257 7", nullptr));
        QTableWidgetItem *___qtablewidgetitem47 = tableWidget->item(2, 2);
        ___qtablewidgetitem47->setText(QCoreApplication::translate("EditPitchBase", "D 7", nullptr));
        QTableWidgetItem *___qtablewidgetitem48 = tableWidget->item(2, 3);
        ___qtablewidgetitem48->setText(QCoreApplication::translate("EditPitchBase", "E\342\231\255 7", nullptr));
        QTableWidgetItem *___qtablewidgetitem49 = tableWidget->item(2, 4);
        ___qtablewidgetitem49->setText(QCoreApplication::translate("EditPitchBase", "E 7", nullptr));
        QTableWidgetItem *___qtablewidgetitem50 = tableWidget->item(2, 5);
        ___qtablewidgetitem50->setText(QCoreApplication::translate("EditPitchBase", "F 7", nullptr));
        QTableWidgetItem *___qtablewidgetitem51 = tableWidget->item(2, 6);
        ___qtablewidgetitem51->setText(QCoreApplication::translate("EditPitchBase", "F\342\231\257 7", nullptr));
        QTableWidgetItem *___qtablewidgetitem52 = tableWidget->item(2, 7);
        ___qtablewidgetitem52->setText(QCoreApplication::translate("EditPitchBase", "G 7", nullptr));
        QTableWidgetItem *___qtablewidgetitem53 = tableWidget->item(2, 8);
        ___qtablewidgetitem53->setText(QCoreApplication::translate("EditPitchBase", "A\342\231\255 7", nullptr));
        QTableWidgetItem *___qtablewidgetitem54 = tableWidget->item(2, 9);
        ___qtablewidgetitem54->setText(QCoreApplication::translate("EditPitchBase", "A 7", nullptr));
        QTableWidgetItem *___qtablewidgetitem55 = tableWidget->item(2, 10);
        ___qtablewidgetitem55->setText(QCoreApplication::translate("EditPitchBase", "B\342\231\255 7", nullptr));
        QTableWidgetItem *___qtablewidgetitem56 = tableWidget->item(2, 11);
        ___qtablewidgetitem56->setText(QCoreApplication::translate("EditPitchBase", "B 7", nullptr));
        QTableWidgetItem *___qtablewidgetitem57 = tableWidget->item(2, 12);
        ___qtablewidgetitem57->setText(QCoreApplication::translate("EditPitchBase", "C 8", nullptr));
        QTableWidgetItem *___qtablewidgetitem58 = tableWidget->item(3, 0);
        ___qtablewidgetitem58->setText(QCoreApplication::translate("EditPitchBase", "C 6", nullptr));
        QTableWidgetItem *___qtablewidgetitem59 = tableWidget->item(3, 1);
        ___qtablewidgetitem59->setText(QCoreApplication::translate("EditPitchBase", "C\342\231\257 6", nullptr));
        QTableWidgetItem *___qtablewidgetitem60 = tableWidget->item(3, 2);
        ___qtablewidgetitem60->setText(QCoreApplication::translate("EditPitchBase", "D 6", nullptr));
        QTableWidgetItem *___qtablewidgetitem61 = tableWidget->item(3, 3);
        ___qtablewidgetitem61->setText(QCoreApplication::translate("EditPitchBase", "E\342\231\255 6", nullptr));
        QTableWidgetItem *___qtablewidgetitem62 = tableWidget->item(3, 4);
        ___qtablewidgetitem62->setText(QCoreApplication::translate("EditPitchBase", "E 6", nullptr));
        QTableWidgetItem *___qtablewidgetitem63 = tableWidget->item(3, 5);
        ___qtablewidgetitem63->setText(QCoreApplication::translate("EditPitchBase", "F 6", nullptr));
        QTableWidgetItem *___qtablewidgetitem64 = tableWidget->item(3, 6);
        ___qtablewidgetitem64->setText(QCoreApplication::translate("EditPitchBase", "F\342\231\257 6", nullptr));
        QTableWidgetItem *___qtablewidgetitem65 = tableWidget->item(3, 7);
        ___qtablewidgetitem65->setText(QCoreApplication::translate("EditPitchBase", "G 6", nullptr));
        QTableWidgetItem *___qtablewidgetitem66 = tableWidget->item(3, 8);
        ___qtablewidgetitem66->setText(QCoreApplication::translate("EditPitchBase", "A\342\231\255 6", nullptr));
        QTableWidgetItem *___qtablewidgetitem67 = tableWidget->item(3, 9);
        ___qtablewidgetitem67->setText(QCoreApplication::translate("EditPitchBase", "A 6", nullptr));
        QTableWidgetItem *___qtablewidgetitem68 = tableWidget->item(3, 10);
        ___qtablewidgetitem68->setText(QCoreApplication::translate("EditPitchBase", "B\342\231\255 6", nullptr));
        QTableWidgetItem *___qtablewidgetitem69 = tableWidget->item(3, 11);
        ___qtablewidgetitem69->setText(QCoreApplication::translate("EditPitchBase", "B 6", nullptr));
        QTableWidgetItem *___qtablewidgetitem70 = tableWidget->item(3, 12);
        ___qtablewidgetitem70->setText(QCoreApplication::translate("EditPitchBase", "C 7", nullptr));
        QTableWidgetItem *___qtablewidgetitem71 = tableWidget->item(4, 0);
        ___qtablewidgetitem71->setText(QCoreApplication::translate("EditPitchBase", "C 5", nullptr));
        QTableWidgetItem *___qtablewidgetitem72 = tableWidget->item(4, 1);
        ___qtablewidgetitem72->setText(QCoreApplication::translate("EditPitchBase", "C\342\231\257 5", nullptr));
        QTableWidgetItem *___qtablewidgetitem73 = tableWidget->item(4, 2);
        ___qtablewidgetitem73->setText(QCoreApplication::translate("EditPitchBase", "D 5", nullptr));
        QTableWidgetItem *___qtablewidgetitem74 = tableWidget->item(4, 3);
        ___qtablewidgetitem74->setText(QCoreApplication::translate("EditPitchBase", "E\342\231\255 5", nullptr));
        QTableWidgetItem *___qtablewidgetitem75 = tableWidget->item(4, 4);
        ___qtablewidgetitem75->setText(QCoreApplication::translate("EditPitchBase", "E 5", nullptr));
        QTableWidgetItem *___qtablewidgetitem76 = tableWidget->item(4, 5);
        ___qtablewidgetitem76->setText(QCoreApplication::translate("EditPitchBase", "F 5", nullptr));
        QTableWidgetItem *___qtablewidgetitem77 = tableWidget->item(4, 6);
        ___qtablewidgetitem77->setText(QCoreApplication::translate("EditPitchBase", "F\342\231\257 5", nullptr));
        QTableWidgetItem *___qtablewidgetitem78 = tableWidget->item(4, 7);
        ___qtablewidgetitem78->setText(QCoreApplication::translate("EditPitchBase", "G 5", nullptr));
        QTableWidgetItem *___qtablewidgetitem79 = tableWidget->item(4, 8);
        ___qtablewidgetitem79->setText(QCoreApplication::translate("EditPitchBase", "A\342\231\255 5", nullptr));
        QTableWidgetItem *___qtablewidgetitem80 = tableWidget->item(4, 9);
        ___qtablewidgetitem80->setText(QCoreApplication::translate("EditPitchBase", "A 5", nullptr));
        QTableWidgetItem *___qtablewidgetitem81 = tableWidget->item(4, 10);
        ___qtablewidgetitem81->setText(QCoreApplication::translate("EditPitchBase", "B\342\231\255 5", nullptr));
        QTableWidgetItem *___qtablewidgetitem82 = tableWidget->item(4, 11);
        ___qtablewidgetitem82->setText(QCoreApplication::translate("EditPitchBase", "B 5", nullptr));
        QTableWidgetItem *___qtablewidgetitem83 = tableWidget->item(4, 12);
        ___qtablewidgetitem83->setText(QCoreApplication::translate("EditPitchBase", "C 6", nullptr));
        QTableWidgetItem *___qtablewidgetitem84 = tableWidget->item(5, 0);
        ___qtablewidgetitem84->setText(QCoreApplication::translate("EditPitchBase", "C 4", nullptr));
        QTableWidgetItem *___qtablewidgetitem85 = tableWidget->item(5, 1);
        ___qtablewidgetitem85->setText(QCoreApplication::translate("EditPitchBase", "C\342\231\257 4", nullptr));
        QTableWidgetItem *___qtablewidgetitem86 = tableWidget->item(5, 2);
        ___qtablewidgetitem86->setText(QCoreApplication::translate("EditPitchBase", "D 4", nullptr));
        QTableWidgetItem *___qtablewidgetitem87 = tableWidget->item(5, 3);
        ___qtablewidgetitem87->setText(QCoreApplication::translate("EditPitchBase", "E\342\231\255 4", nullptr));
        QTableWidgetItem *___qtablewidgetitem88 = tableWidget->item(5, 4);
        ___qtablewidgetitem88->setText(QCoreApplication::translate("EditPitchBase", "E 4", nullptr));
        QTableWidgetItem *___qtablewidgetitem89 = tableWidget->item(5, 5);
        ___qtablewidgetitem89->setText(QCoreApplication::translate("EditPitchBase", "F 4", nullptr));
        QTableWidgetItem *___qtablewidgetitem90 = tableWidget->item(5, 6);
        ___qtablewidgetitem90->setText(QCoreApplication::translate("EditPitchBase", "F\342\231\257 4", nullptr));
        QTableWidgetItem *___qtablewidgetitem91 = tableWidget->item(5, 7);
        ___qtablewidgetitem91->setText(QCoreApplication::translate("EditPitchBase", "G 4", nullptr));
        QTableWidgetItem *___qtablewidgetitem92 = tableWidget->item(5, 8);
        ___qtablewidgetitem92->setText(QCoreApplication::translate("EditPitchBase", "A\342\231\255 4", nullptr));
        QTableWidgetItem *___qtablewidgetitem93 = tableWidget->item(5, 9);
        ___qtablewidgetitem93->setText(QCoreApplication::translate("EditPitchBase", "A 4", nullptr));
        QTableWidgetItem *___qtablewidgetitem94 = tableWidget->item(5, 10);
        ___qtablewidgetitem94->setText(QCoreApplication::translate("EditPitchBase", "B\342\231\255 4", nullptr));
        QTableWidgetItem *___qtablewidgetitem95 = tableWidget->item(5, 11);
        ___qtablewidgetitem95->setText(QCoreApplication::translate("EditPitchBase", "B 4", nullptr));
        QTableWidgetItem *___qtablewidgetitem96 = tableWidget->item(5, 12);
        ___qtablewidgetitem96->setText(QCoreApplication::translate("EditPitchBase", "C 5", nullptr));
        QTableWidgetItem *___qtablewidgetitem97 = tableWidget->item(6, 0);
        ___qtablewidgetitem97->setText(QCoreApplication::translate("EditPitchBase", "C 3", nullptr));
        QTableWidgetItem *___qtablewidgetitem98 = tableWidget->item(6, 1);
        ___qtablewidgetitem98->setText(QCoreApplication::translate("EditPitchBase", "C\342\231\257 3", nullptr));
        QTableWidgetItem *___qtablewidgetitem99 = tableWidget->item(6, 2);
        ___qtablewidgetitem99->setText(QCoreApplication::translate("EditPitchBase", "D 3", nullptr));
        QTableWidgetItem *___qtablewidgetitem100 = tableWidget->item(6, 3);
        ___qtablewidgetitem100->setText(QCoreApplication::translate("EditPitchBase", "E\342\231\255 3", nullptr));
        QTableWidgetItem *___qtablewidgetitem101 = tableWidget->item(6, 4);
        ___qtablewidgetitem101->setText(QCoreApplication::translate("EditPitchBase", "E 3", nullptr));
        QTableWidgetItem *___qtablewidgetitem102 = tableWidget->item(6, 5);
        ___qtablewidgetitem102->setText(QCoreApplication::translate("EditPitchBase", "F 3", nullptr));
        QTableWidgetItem *___qtablewidgetitem103 = tableWidget->item(6, 6);
        ___qtablewidgetitem103->setText(QCoreApplication::translate("EditPitchBase", "F\342\231\257 3", nullptr));
        QTableWidgetItem *___qtablewidgetitem104 = tableWidget->item(6, 7);
        ___qtablewidgetitem104->setText(QCoreApplication::translate("EditPitchBase", "G 3", nullptr));
        QTableWidgetItem *___qtablewidgetitem105 = tableWidget->item(6, 8);
        ___qtablewidgetitem105->setText(QCoreApplication::translate("EditPitchBase", "A\342\231\255 3", nullptr));
        QTableWidgetItem *___qtablewidgetitem106 = tableWidget->item(6, 9);
        ___qtablewidgetitem106->setText(QCoreApplication::translate("EditPitchBase", "A 3", nullptr));
        QTableWidgetItem *___qtablewidgetitem107 = tableWidget->item(6, 10);
        ___qtablewidgetitem107->setText(QCoreApplication::translate("EditPitchBase", "B\342\231\255 3", nullptr));
        QTableWidgetItem *___qtablewidgetitem108 = tableWidget->item(6, 11);
        ___qtablewidgetitem108->setText(QCoreApplication::translate("EditPitchBase", "B 3", nullptr));
        QTableWidgetItem *___qtablewidgetitem109 = tableWidget->item(6, 12);
        ___qtablewidgetitem109->setText(QCoreApplication::translate("EditPitchBase", "C 4", nullptr));
        QTableWidgetItem *___qtablewidgetitem110 = tableWidget->item(7, 0);
        ___qtablewidgetitem110->setText(QCoreApplication::translate("EditPitchBase", "C 2", nullptr));
        QTableWidgetItem *___qtablewidgetitem111 = tableWidget->item(7, 1);
        ___qtablewidgetitem111->setText(QCoreApplication::translate("EditPitchBase", "C\342\231\257 2", nullptr));
        QTableWidgetItem *___qtablewidgetitem112 = tableWidget->item(7, 2);
        ___qtablewidgetitem112->setText(QCoreApplication::translate("EditPitchBase", "D 2", nullptr));
        QTableWidgetItem *___qtablewidgetitem113 = tableWidget->item(7, 3);
        ___qtablewidgetitem113->setText(QCoreApplication::translate("EditPitchBase", "E\342\231\255 2", nullptr));
        QTableWidgetItem *___qtablewidgetitem114 = tableWidget->item(7, 4);
        ___qtablewidgetitem114->setText(QCoreApplication::translate("EditPitchBase", "E 2", nullptr));
        QTableWidgetItem *___qtablewidgetitem115 = tableWidget->item(7, 5);
        ___qtablewidgetitem115->setText(QCoreApplication::translate("EditPitchBase", "F 2", nullptr));
        QTableWidgetItem *___qtablewidgetitem116 = tableWidget->item(7, 6);
        ___qtablewidgetitem116->setText(QCoreApplication::translate("EditPitchBase", "F\342\231\257 2", nullptr));
        QTableWidgetItem *___qtablewidgetitem117 = tableWidget->item(7, 7);
        ___qtablewidgetitem117->setText(QCoreApplication::translate("EditPitchBase", "G 2", nullptr));
        QTableWidgetItem *___qtablewidgetitem118 = tableWidget->item(7, 8);
        ___qtablewidgetitem118->setText(QCoreApplication::translate("EditPitchBase", "A\342\231\255 2", nullptr));
        QTableWidgetItem *___qtablewidgetitem119 = tableWidget->item(7, 9);
        ___qtablewidgetitem119->setText(QCoreApplication::translate("EditPitchBase", "A 2", nullptr));
        QTableWidgetItem *___qtablewidgetitem120 = tableWidget->item(7, 10);
        ___qtablewidgetitem120->setText(QCoreApplication::translate("EditPitchBase", "B\342\231\255 2", nullptr));
        QTableWidgetItem *___qtablewidgetitem121 = tableWidget->item(7, 11);
        ___qtablewidgetitem121->setText(QCoreApplication::translate("EditPitchBase", "B 2", nullptr));
        QTableWidgetItem *___qtablewidgetitem122 = tableWidget->item(7, 12);
        ___qtablewidgetitem122->setText(QCoreApplication::translate("EditPitchBase", "C 3", nullptr));
        QTableWidgetItem *___qtablewidgetitem123 = tableWidget->item(8, 0);
        ___qtablewidgetitem123->setText(QCoreApplication::translate("EditPitchBase", "C 1", nullptr));
        QTableWidgetItem *___qtablewidgetitem124 = tableWidget->item(8, 1);
        ___qtablewidgetitem124->setText(QCoreApplication::translate("EditPitchBase", "C\342\231\257 1", nullptr));
        QTableWidgetItem *___qtablewidgetitem125 = tableWidget->item(8, 2);
        ___qtablewidgetitem125->setText(QCoreApplication::translate("EditPitchBase", "D 1", nullptr));
        QTableWidgetItem *___qtablewidgetitem126 = tableWidget->item(8, 3);
        ___qtablewidgetitem126->setText(QCoreApplication::translate("EditPitchBase", "E\342\231\255 1", nullptr));
        QTableWidgetItem *___qtablewidgetitem127 = tableWidget->item(8, 4);
        ___qtablewidgetitem127->setText(QCoreApplication::translate("EditPitchBase", "E 1", nullptr));
        QTableWidgetItem *___qtablewidgetitem128 = tableWidget->item(8, 5);
        ___qtablewidgetitem128->setText(QCoreApplication::translate("EditPitchBase", "F 1", nullptr));
        QTableWidgetItem *___qtablewidgetitem129 = tableWidget->item(8, 6);
        ___qtablewidgetitem129->setText(QCoreApplication::translate("EditPitchBase", "F\342\231\257 1", nullptr));
        QTableWidgetItem *___qtablewidgetitem130 = tableWidget->item(8, 7);
        ___qtablewidgetitem130->setText(QCoreApplication::translate("EditPitchBase", "G 1", nullptr));
        QTableWidgetItem *___qtablewidgetitem131 = tableWidget->item(8, 8);
        ___qtablewidgetitem131->setText(QCoreApplication::translate("EditPitchBase", "A\342\231\255 1", nullptr));
        QTableWidgetItem *___qtablewidgetitem132 = tableWidget->item(8, 9);
        ___qtablewidgetitem132->setText(QCoreApplication::translate("EditPitchBase", "A 1", nullptr));
        QTableWidgetItem *___qtablewidgetitem133 = tableWidget->item(8, 10);
        ___qtablewidgetitem133->setText(QCoreApplication::translate("EditPitchBase", "B\342\231\255 1", nullptr));
        QTableWidgetItem *___qtablewidgetitem134 = tableWidget->item(8, 11);
        ___qtablewidgetitem134->setText(QCoreApplication::translate("EditPitchBase", "B 1", nullptr));
        QTableWidgetItem *___qtablewidgetitem135 = tableWidget->item(8, 12);
        ___qtablewidgetitem135->setText(QCoreApplication::translate("EditPitchBase", "C 2", nullptr));
        QTableWidgetItem *___qtablewidgetitem136 = tableWidget->item(9, 0);
        ___qtablewidgetitem136->setText(QCoreApplication::translate("EditPitchBase", "C 0", nullptr));
        QTableWidgetItem *___qtablewidgetitem137 = tableWidget->item(9, 1);
        ___qtablewidgetitem137->setText(QCoreApplication::translate("EditPitchBase", "C\342\231\257 0", nullptr));
        QTableWidgetItem *___qtablewidgetitem138 = tableWidget->item(9, 2);
        ___qtablewidgetitem138->setText(QCoreApplication::translate("EditPitchBase", "D 0", nullptr));
        QTableWidgetItem *___qtablewidgetitem139 = tableWidget->item(9, 3);
        ___qtablewidgetitem139->setText(QCoreApplication::translate("EditPitchBase", "E\342\231\255 0", nullptr));
        QTableWidgetItem *___qtablewidgetitem140 = tableWidget->item(9, 4);
        ___qtablewidgetitem140->setText(QCoreApplication::translate("EditPitchBase", "E 0", nullptr));
        QTableWidgetItem *___qtablewidgetitem141 = tableWidget->item(9, 5);
        ___qtablewidgetitem141->setText(QCoreApplication::translate("EditPitchBase", "F 0", nullptr));
        QTableWidgetItem *___qtablewidgetitem142 = tableWidget->item(9, 6);
        ___qtablewidgetitem142->setText(QCoreApplication::translate("EditPitchBase", "F\342\231\257 0", nullptr));
        QTableWidgetItem *___qtablewidgetitem143 = tableWidget->item(9, 7);
        ___qtablewidgetitem143->setText(QCoreApplication::translate("EditPitchBase", "G 0", nullptr));
        QTableWidgetItem *___qtablewidgetitem144 = tableWidget->item(9, 8);
        ___qtablewidgetitem144->setText(QCoreApplication::translate("EditPitchBase", "A\342\231\255 0", nullptr));
        QTableWidgetItem *___qtablewidgetitem145 = tableWidget->item(9, 9);
        ___qtablewidgetitem145->setText(QCoreApplication::translate("EditPitchBase", "A 0", nullptr));
        QTableWidgetItem *___qtablewidgetitem146 = tableWidget->item(9, 10);
        ___qtablewidgetitem146->setText(QCoreApplication::translate("EditPitchBase", "B\342\231\255 0", nullptr));
        QTableWidgetItem *___qtablewidgetitem147 = tableWidget->item(9, 11);
        ___qtablewidgetitem147->setText(QCoreApplication::translate("EditPitchBase", "B 0", nullptr));
        QTableWidgetItem *___qtablewidgetitem148 = tableWidget->item(9, 12);
        ___qtablewidgetitem148->setText(QCoreApplication::translate("EditPitchBase", "C 1", nullptr));
        QTableWidgetItem *___qtablewidgetitem149 = tableWidget->item(10, 0);
        ___qtablewidgetitem149->setText(QCoreApplication::translate("EditPitchBase", "C -1", nullptr));
        QTableWidgetItem *___qtablewidgetitem150 = tableWidget->item(10, 1);
        ___qtablewidgetitem150->setText(QCoreApplication::translate("EditPitchBase", "C\342\231\257 -1", nullptr));
        QTableWidgetItem *___qtablewidgetitem151 = tableWidget->item(10, 2);
        ___qtablewidgetitem151->setText(QCoreApplication::translate("EditPitchBase", "D -1", nullptr));
        QTableWidgetItem *___qtablewidgetitem152 = tableWidget->item(10, 3);
        ___qtablewidgetitem152->setText(QCoreApplication::translate("EditPitchBase", "E\342\231\255 -1", nullptr));
        QTableWidgetItem *___qtablewidgetitem153 = tableWidget->item(10, 4);
        ___qtablewidgetitem153->setText(QCoreApplication::translate("EditPitchBase", "E -1", nullptr));
        QTableWidgetItem *___qtablewidgetitem154 = tableWidget->item(10, 5);
        ___qtablewidgetitem154->setText(QCoreApplication::translate("EditPitchBase", "F -1", nullptr));
        QTableWidgetItem *___qtablewidgetitem155 = tableWidget->item(10, 6);
        ___qtablewidgetitem155->setText(QCoreApplication::translate("EditPitchBase", "F\342\231\257 -1", nullptr));
        QTableWidgetItem *___qtablewidgetitem156 = tableWidget->item(10, 7);
        ___qtablewidgetitem156->setText(QCoreApplication::translate("EditPitchBase", "G -1", nullptr));
        QTableWidgetItem *___qtablewidgetitem157 = tableWidget->item(10, 8);
        ___qtablewidgetitem157->setText(QCoreApplication::translate("EditPitchBase", "A\342\231\255 -1", nullptr));
        QTableWidgetItem *___qtablewidgetitem158 = tableWidget->item(10, 9);
        ___qtablewidgetitem158->setText(QCoreApplication::translate("EditPitchBase", "A -1", nullptr));
        QTableWidgetItem *___qtablewidgetitem159 = tableWidget->item(10, 10);
        ___qtablewidgetitem159->setText(QCoreApplication::translate("EditPitchBase", "B\342\231\255 -1", nullptr));
        QTableWidgetItem *___qtablewidgetitem160 = tableWidget->item(10, 11);
        ___qtablewidgetitem160->setText(QCoreApplication::translate("EditPitchBase", "B -1", nullptr));
        QTableWidgetItem *___qtablewidgetitem161 = tableWidget->item(10, 12);
        ___qtablewidgetitem161->setText(QCoreApplication::translate("EditPitchBase", "C 0", nullptr));
        tableWidget->setSortingEnabled(__sortingEnabled);

    } // retranslateUi

};

namespace Ui {
    class EditPitchBase: public Ui_EditPitchBase {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_EDITPITCH_H
