// This file is autogenerated. Changes will be overwritten.
#include "OTUN7GXZT4/moc_articulationpatternitem.cpp"
#include "OTUN7GXZT4/moc_articulationpatternsegmentitem.cpp"
#include "OTUN7GXZT4/moc_articulationsprofileeditormodel.cpp"
