/****************************************************************************
** Meta object code from reading C++ file 'iconcodes.h'
**
** Created by: The Qt Meta Object Compiler version 68 (Qt 6.7.0)
**
** WARNING! All changes made in this file will be lost!
*****************************************************************************/

#include "../../../../../../../src/framework/ui/view/iconcodes.h"
#include <QtCore/qmetatype.h>

#include <QtCore/qtmochelpers.h>

#include <memory>


#include <QtCore/qxptype_traits.h>
#if !defined(Q_MOC_OUTPUT_REVISION)
#error "The header file 'iconcodes.h' doesn't include <QObject>."
#elif Q_MOC_OUTPUT_REVISION != 68
#error "This file was generated using the moc from 6.7.0. It"
#error "cannot be used with the include files from this version of Qt."
#error "(The moc has changed too much.)"
#endif

#ifndef Q_CONSTINIT
#define Q_CONSTINIT
#endif

QT_WARNING_PUSH
QT_WARNING_DISABLE_DEPRECATED
QT_WARNING_DISABLE_GCC("-Wuseless-cast")
namespace {

#ifdef QT_MOC_HAS_STRINGDATA
struct qt_meta_stringdata_CLASSmuseSCOPEuiSCOPEIconCodeENDCLASS_t {};
constexpr auto qt_meta_stringdata_CLASSmuseSCOPEuiSCOPEIconCodeENDCLASS = QtMocHelpers::stringData(
    "muse::ui::IconCode",
    "Code",
    "SMALL_ARROW_UP",
    "SMALL_ARROW_RIGHT",
    "SMALL_ARROW_DOWN",
    "MENU_THREE_DOTS",
    "CLOSE_X_ROUNDED",
    "SPLIT_OUT_ARROWS",
    "ZOOM_OUT",
    "SEARCH",
    "ZOOM_IN",
    "UNDO",
    "REDO",
    "PAGE_VIEW",
    "CONTINUOUS_VIEW",
    "PLAY",
    "STOP",
    "LOOP",
    "METRONOME",
    "TUNING_FORK",
    "NEW_FILE",
    "OPEN_FILE",
    "SHARE_FILE",
    "CLOUD_FILE",
    "REWIND",
    "MIXER",
    "CONFIGURE",
    "SAVE",
    "PLUS",
    "MINUS",
    "DELETE_TANK",
    "FEEDBACK",
    "LINK",
    "TICK",
    "CROSS",
    "TICK_RIGHT_ANGLE",
    "HORIZONTAL",
    "VERTICAL",
    "ARROW_RIGHT",
    "ARROW_LEFT",
    "ARROW_DOWN",
    "ARROW_UP",
    "POSITION_ARROWS",
    "TEXT_ALIGN_BASELINE",
    "TEXT_ALIGN_BOTTOM",
    "TEXT_ALIGN_TOP",
    "TEXT_ALIGN_MIDDLE",
    "TEXT_ALIGN_LEFT",
    "TEXT_ALIGN_CENTER",
    "TEXT_ALIGN_RIGHT",
    "TEXT_ITALIC",
    "TEXT_UNDERLINE",
    "TEXT_BOLD",
    "TEXT_STRIKE",
    "APPLY_GLOBAL_STYLE",
    "HAIRPIN",
    "ACCIDENTAL_SHARP",
    "SLUR",
    "DYNAMIC_FORTE",
    "CRESCENDO_LINE",
    "FRAME_SQUARE",
    "FRAME_CIRCLE",
    "MUSIC_NOTES",
    "TEXT_SUBSCRIPT",
    "TEXT_SUPERSCRIPT",
    "AUDIO",
    "EYE_OPEN",
    "EYE_CLOSED",
    "SETTINGS_COG",
    "BEAM_FEATHERING_RIGHT_HEIGHT",
    "BEAM_FEATHERING_LEFT_HEIGHT",
    "BEAM_HEIGHT_LEFT",
    "BEAM_HEIGHT_RIGHT",
    "LOCK_CLOSED",
    "LOCK_OPEN",
    "DOT_ABOVE_LINE",
    "DOT_BELOW_LINE",
    "TEXT_BELOW_STAFF",
    "TEXT_ABOVE_STAFF",
    "GLISSANDO",
    "EDIT",
    "TIME_SIGNATURE",
    "PEDAL_MARKING",
    "MARKER",
    "JUMP",
    "REPEAT_START",
    "FERMATA",
    "SECTION_BREAK",
    "SPACER",
    "VERTICAL_FRAME",
    "HORIZONTAL_FRAME",
    "TEXT_FRAME",
    "ORNAMENT",
    "ARTICULATION",
    "BRACKET",
    "BRACE",
    "CLEF_BASS",
    "MORTAR_BOARD",
    "FRETBOARD_DIAGRAM",
    "FRETBOARD_MARKER_TRIANGLE",
    "FRETBOARD_MARKER_CIRCLE_OUTLINE",
    "FRETBOARD_MARKER_CIRCLE_FILLED",
    "AMBITUS",
    "AMBITUS_LEANING_LEFT",
    "AMBITUS_LEANING_RIGHT",
    "BRACKET_PARENTHESES",
    "BRACKET_PARENTHESES_SQUARE",
    "SPLIT_VIEW_HORIZONTAL",
    "SPLIT_VIEW_VERTICAL",
    "KEY_SIGNATURE",
    "LINE_DASHED",
    "LINE_WIDE_DASHED",
    "ZOOM_TOGGLE",
    "FIT_SELECTION",
    "FIT_PROJECT",
    "TRIM_AUDIO_OUTSIDE_SELECTION",
    "SILENCE_AUDIO_SELECTION",
    "LINE_DOTTED",
    "LINE_NORMAL",
    "LINE_WITH_END_HOOK",
    "LINE_WITH_ANGLED_END_HOOK",
    "LINE_PEDAL_STAR_ENDING",
    "BEAM_FEATHERED_ACCELERATE",
    "BEAM_FEATHERED_DECELERATE",
    "RIGHT_GAP",
    "LEFT_GAP",
    "GAP_BELOW",
    "GAP_ABOVE",
    "LEFT_MARGIN",
    "RIGHT_MARGIN",
    "BOTTOM_MARGIN",
    "TOP_MARGIN",
    "MIDI_INPUT",
    "ACCOUNT",
    "STAR",
    "LINE_WITH_TWO_INVERTED_HOOKS",
    "LINE_WITH_T_LIKE_END_HOOK",
    "LINE_WITH_T_LINE_START_HOOK",
    "LINE_WITH_START_HOOK",
    "LINE_WITH_ANGLED_START_HOOK",
    "LINE_WITH_INVERTED_START_HOOK",
    "IMAGE_MOUNTAINS",
    "GRADUATION_CAP",
    "SCORE",
    "CLEF_TREBLE",
    "AUTO_TEXT",
    "BEAM_NONE",
    "BEAM_BREAK_LEFT",
    "BEAM_JOIN",
    "BEAM_BREAK_INNER_8TH",
    "BEAM_BREAK_INNER_16TH",
    "QUESTION_MARK",
    "NOTE_HEAD_QUARTER",
    "NOTE_HEAD_HALF",
    "NOTE_HEAD_WHOLE",
    "NOTE_HEAD_BREVIS",
    "NOTE_HEAD",
    "NOTE_HEAD_PARENTHESES",
    "PLAY_REPEATS",
    "BARLINE_WINGED",
    "BARLINE_UNWINGED",
    "ORIENTATION_PORTRAIT",
    "ORIENTATION_LANDSCAPE",
    "CHORD_SYMBOL",
    "GUITAR_BEND",
    "MULTIMEASURE_REST",
    "IMPORT",
    "UPDATE",
    "OPEN_LINK",
    "GUITAR_TREMOLO_BAR",
    "SHORTCUTS",
    "TREMOLO_TWO_NOTES",
    "TREMOLO_STYLE_DEFAULT",
    "TREMOLO_STYLE_TRADITIONAL",
    "TREMOLO_ONE_NOTE",
    "TREMOLO_STYLE_TRADITIONAL_ALTERNATE",
    "LONGO",
    "NOTE_WHOLE_DOUBLE",
    "NOTE_WHOLE",
    "NOTE_HALF",
    "NOTE_QUARTER",
    "NOTE_8TH",
    "NOTE_16TH",
    "NOTE_32ND",
    "NOTE_64TH",
    "NOTE_128TH",
    "NOTE_256TH",
    "NOTE_512TH",
    "NOTE_1024TH",
    "REST",
    "NOTE_DOTTED",
    "NOTE_TIE",
    "NOTE_FLIP",
    "NOTE_SLUR",
    "NOTE_TUPLET",
    "KEY_SIGNATURE_NONE",
    "KEY_SIGNATURE_1_SHARP",
    "KEY_SIGNATURE_2_SHARPS",
    "KEY_SIGNATURE_3_SHARPS",
    "KEY_SIGNATURE_4_SHARPS",
    "KEY_SIGNATURE_5_SHARPS",
    "KEY_SIGNATURE_6_SHARPS",
    "KEY_SIGNATURE_7_SHARPS",
    "KEY_SIGNATURE_1_FLAT",
    "KEY_SIGNATURE_2_FLAT",
    "KEY_SIGNATURE_3_FLAT",
    "KEY_SIGNATURE_4_FLAT",
    "KEY_SIGNATURE_5_FLAT",
    "KEY_SIGNATURE_6_FLAT",
    "KEY_SIGNATURE_7_FLAT",
    "SHARP",
    "NATURAL",
    "FLAT",
    "FLAT_DOUBLE",
    "SHARP_DOUBLE",
    "MARCATO",
    "ACCENT",
    "TENUTO",
    "STACCATO",
    "BYPASS",
    "VOICE_1",
    "VOICE_2",
    "VOICE_3",
    "VOICE_4",
    "NOTE_DOTTED_2",
    "NOTE_DOTTED_3",
    "NOTE_DOTTED_4",
    "COPY",
    "PASTE",
    "CUT",
    "CHEVRON_RIGHT",
    "CHEVRON_LEFT",
    "NOTE_PLUS",
    "NOTE_TO_RIGHT",
    "RHYTHM_ONLY",
    "RE_PITCH",
    "FOOT_PEDAL",
    "TOOLBAR_GRIP",
    "GRID",
    "PAGE",
    "LIST",
    "CAMERA",
    "CONTINUOUS_VIEW_VERTICAL",
    "PAN_SCORE",
    "COUNT_IN",
    "GLOBE",
    "PRINT",
    "DOWN",
    "UP",
    "LOOP_IN",
    "LOOP_OUT",
    "PAUSE",
    "WARNING",
    "INFO",
    "ERROR",
    "QUESTION",
    "MUTE",
    "SOLO",
    "OTTAVA",
    "PALM_MUTE",
    "LET_RING",
    "VOLTA",
    "VIBRATO",
    "DIMINUENDO",
    "CRESCENDO",
    "MICROPHONE",
    "APP_MINIMIZE",
    "APP_MAXIMIZE",
    "APP_UNMAXIMIZE",
    "APP_CLOSE",
    "NOTEFLAGS_TRADITIONAL",
    "NOTEFLAGS_STRAIGHT",
    "TUPLET_NUMBER_WITH_BRACKETS",
    "TUPLET_NUMBER_ONLY",
    "USE_WIDE_BEAMS_REGULAR",
    "USE_WIDE_BEAMS_WIDE",
    "ACCIACCATURA",
    "APPOGGIATURA",
    "GRACE4",
    "GRACE16",
    "GRACE32",
    "GRACE8_AFTER",
    "GRACE16_AFTER",
    "GRACE32_AFTER",
    "MEASURE_REPEAT",
    "INSERT_ONE_MEASURE",
    "STAFF_TYPE_CHANGE",
    "CLOUD",
    "WAVEFORM",
    "CROSS_STAFF_BEAMING",
    "TEMPO_CHANGE",
    "PLUGIN",
    "LYRICS",
    "LEARN",
    "SPECTROGRAM",
    "SPECTROGRAM_BOX_SELECTION",
    "BRUSH",
    "PLAY_FILL",
    "STOP_FILL",
    "REWIND_START_FILL",
    "REWIND_END_FILL",
    "RECORD_FILL",
    "PAUSE_FILL",
    "REST_8TH",
    "CIRCLE",
    "SHARE_AUDIO",
    "DYNAMIC_CENTER_1",
    "DYNAMIC_CENTER_2",
    "EXPRESSION",
    "CLOUD_FILL",
    "BRAILLE",
    "AUTOMATION",
    "GUITAR_BEND_REGULAR",
    "GUITAR_PRE_BEND",
    "GUITAR_GRACE_NOTE_BEND",
    "GUITAR_SLIGHT_BEND",
    "GUITAR_BEND_STYLE_1",
    "GUITAR_BEND_STYLE_FULL",
    "TIE_OUTSIDE",
    "TIE_INSIDE",
    "TIE_CHORD_OUTSIDE",
    "TIE_CHORD_INSIDE",
    "TRIANGLE_SYMBOL",
    "NONE"
);
#else  // !QT_MOC_HAS_STRINGDATA
#error "qtmochelpers.h not found or too old."
#endif // !QT_MOC_HAS_STRINGDATA
} // unnamed namespace

Q_CONSTINIT static const uint qt_meta_data_CLASSmuseSCOPEuiSCOPEIconCodeENDCLASS[] = {

 // content:
      12,       // revision
       0,       // classname
       0,    0, // classinfo
       0,    0, // methods
       0,    0, // properties
       1,   14, // enums/sets
       0,    0, // constructors
       4,       // flags
       0,       // signalCount

 // enums: name, alias, flags, count, data
       1,    1, 0x2,  322,   19,

 // enum data: key, value
       2, uint(muse::ui::IconCode::Code::SMALL_ARROW_UP),
       3, uint(muse::ui::IconCode::Code::SMALL_ARROW_RIGHT),
       4, uint(muse::ui::IconCode::Code::SMALL_ARROW_DOWN),
       5, uint(muse::ui::IconCode::Code::MENU_THREE_DOTS),
       6, uint(muse::ui::IconCode::Code::CLOSE_X_ROUNDED),
       7, uint(muse::ui::IconCode::Code::SPLIT_OUT_ARROWS),
       8, uint(muse::ui::IconCode::Code::ZOOM_OUT),
       9, uint(muse::ui::IconCode::Code::SEARCH),
      10, uint(muse::ui::IconCode::Code::ZOOM_IN),
      11, uint(muse::ui::IconCode::Code::UNDO),
      12, uint(muse::ui::IconCode::Code::REDO),
      13, uint(muse::ui::IconCode::Code::PAGE_VIEW),
      14, uint(muse::ui::IconCode::Code::CONTINUOUS_VIEW),
      15, uint(muse::ui::IconCode::Code::PLAY),
      16, uint(muse::ui::IconCode::Code::STOP),
      17, uint(muse::ui::IconCode::Code::LOOP),
      18, uint(muse::ui::IconCode::Code::METRONOME),
      19, uint(muse::ui::IconCode::Code::TUNING_FORK),
      20, uint(muse::ui::IconCode::Code::NEW_FILE),
      21, uint(muse::ui::IconCode::Code::OPEN_FILE),
      22, uint(muse::ui::IconCode::Code::SHARE_FILE),
      23, uint(muse::ui::IconCode::Code::CLOUD_FILE),
      24, uint(muse::ui::IconCode::Code::REWIND),
      25, uint(muse::ui::IconCode::Code::MIXER),
      26, uint(muse::ui::IconCode::Code::CONFIGURE),
      27, uint(muse::ui::IconCode::Code::SAVE),
      28, uint(muse::ui::IconCode::Code::PLUS),
      29, uint(muse::ui::IconCode::Code::MINUS),
      30, uint(muse::ui::IconCode::Code::DELETE_TANK),
      31, uint(muse::ui::IconCode::Code::FEEDBACK),
      32, uint(muse::ui::IconCode::Code::LINK),
      33, uint(muse::ui::IconCode::Code::TICK),
      34, uint(muse::ui::IconCode::Code::CROSS),
      35, uint(muse::ui::IconCode::Code::TICK_RIGHT_ANGLE),
      36, uint(muse::ui::IconCode::Code::HORIZONTAL),
      37, uint(muse::ui::IconCode::Code::VERTICAL),
      38, uint(muse::ui::IconCode::Code::ARROW_RIGHT),
      39, uint(muse::ui::IconCode::Code::ARROW_LEFT),
      40, uint(muse::ui::IconCode::Code::ARROW_DOWN),
      41, uint(muse::ui::IconCode::Code::ARROW_UP),
      42, uint(muse::ui::IconCode::Code::POSITION_ARROWS),
      43, uint(muse::ui::IconCode::Code::TEXT_ALIGN_BASELINE),
      44, uint(muse::ui::IconCode::Code::TEXT_ALIGN_BOTTOM),
      45, uint(muse::ui::IconCode::Code::TEXT_ALIGN_TOP),
      46, uint(muse::ui::IconCode::Code::TEXT_ALIGN_MIDDLE),
      47, uint(muse::ui::IconCode::Code::TEXT_ALIGN_LEFT),
      48, uint(muse::ui::IconCode::Code::TEXT_ALIGN_CENTER),
      49, uint(muse::ui::IconCode::Code::TEXT_ALIGN_RIGHT),
      50, uint(muse::ui::IconCode::Code::TEXT_ITALIC),
      51, uint(muse::ui::IconCode::Code::TEXT_UNDERLINE),
      52, uint(muse::ui::IconCode::Code::TEXT_BOLD),
      53, uint(muse::ui::IconCode::Code::TEXT_STRIKE),
      54, uint(muse::ui::IconCode::Code::APPLY_GLOBAL_STYLE),
      55, uint(muse::ui::IconCode::Code::HAIRPIN),
      56, uint(muse::ui::IconCode::Code::ACCIDENTAL_SHARP),
      57, uint(muse::ui::IconCode::Code::SLUR),
      58, uint(muse::ui::IconCode::Code::DYNAMIC_FORTE),
      59, uint(muse::ui::IconCode::Code::CRESCENDO_LINE),
      60, uint(muse::ui::IconCode::Code::FRAME_SQUARE),
      61, uint(muse::ui::IconCode::Code::FRAME_CIRCLE),
      62, uint(muse::ui::IconCode::Code::MUSIC_NOTES),
      63, uint(muse::ui::IconCode::Code::TEXT_SUBSCRIPT),
      64, uint(muse::ui::IconCode::Code::TEXT_SUPERSCRIPT),
      65, uint(muse::ui::IconCode::Code::AUDIO),
      66, uint(muse::ui::IconCode::Code::EYE_OPEN),
      67, uint(muse::ui::IconCode::Code::EYE_CLOSED),
      68, uint(muse::ui::IconCode::Code::SETTINGS_COG),
      69, uint(muse::ui::IconCode::Code::BEAM_FEATHERING_RIGHT_HEIGHT),
      70, uint(muse::ui::IconCode::Code::BEAM_FEATHERING_LEFT_HEIGHT),
      71, uint(muse::ui::IconCode::Code::BEAM_HEIGHT_LEFT),
      72, uint(muse::ui::IconCode::Code::BEAM_HEIGHT_RIGHT),
      73, uint(muse::ui::IconCode::Code::LOCK_CLOSED),
      74, uint(muse::ui::IconCode::Code::LOCK_OPEN),
      75, uint(muse::ui::IconCode::Code::DOT_ABOVE_LINE),
      76, uint(muse::ui::IconCode::Code::DOT_BELOW_LINE),
      77, uint(muse::ui::IconCode::Code::TEXT_BELOW_STAFF),
      78, uint(muse::ui::IconCode::Code::TEXT_ABOVE_STAFF),
      79, uint(muse::ui::IconCode::Code::GLISSANDO),
      80, uint(muse::ui::IconCode::Code::EDIT),
      81, uint(muse::ui::IconCode::Code::TIME_SIGNATURE),
      82, uint(muse::ui::IconCode::Code::PEDAL_MARKING),
      83, uint(muse::ui::IconCode::Code::MARKER),
      84, uint(muse::ui::IconCode::Code::JUMP),
      85, uint(muse::ui::IconCode::Code::REPEAT_START),
      86, uint(muse::ui::IconCode::Code::FERMATA),
      87, uint(muse::ui::IconCode::Code::SECTION_BREAK),
      88, uint(muse::ui::IconCode::Code::SPACER),
      89, uint(muse::ui::IconCode::Code::VERTICAL_FRAME),
      90, uint(muse::ui::IconCode::Code::HORIZONTAL_FRAME),
      91, uint(muse::ui::IconCode::Code::TEXT_FRAME),
      92, uint(muse::ui::IconCode::Code::ORNAMENT),
      93, uint(muse::ui::IconCode::Code::ARTICULATION),
      94, uint(muse::ui::IconCode::Code::BRACKET),
      95, uint(muse::ui::IconCode::Code::BRACE),
      96, uint(muse::ui::IconCode::Code::CLEF_BASS),
      97, uint(muse::ui::IconCode::Code::MORTAR_BOARD),
      98, uint(muse::ui::IconCode::Code::FRETBOARD_DIAGRAM),
      99, uint(muse::ui::IconCode::Code::FRETBOARD_MARKER_TRIANGLE),
     100, uint(muse::ui::IconCode::Code::FRETBOARD_MARKER_CIRCLE_OUTLINE),
     101, uint(muse::ui::IconCode::Code::FRETBOARD_MARKER_CIRCLE_FILLED),
     102, uint(muse::ui::IconCode::Code::AMBITUS),
     103, uint(muse::ui::IconCode::Code::AMBITUS_LEANING_LEFT),
     104, uint(muse::ui::IconCode::Code::AMBITUS_LEANING_RIGHT),
     105, uint(muse::ui::IconCode::Code::BRACKET_PARENTHESES),
     106, uint(muse::ui::IconCode::Code::BRACKET_PARENTHESES_SQUARE),
     107, uint(muse::ui::IconCode::Code::SPLIT_VIEW_HORIZONTAL),
     108, uint(muse::ui::IconCode::Code::SPLIT_VIEW_VERTICAL),
     109, uint(muse::ui::IconCode::Code::KEY_SIGNATURE),
     110, uint(muse::ui::IconCode::Code::LINE_DASHED),
     111, uint(muse::ui::IconCode::Code::LINE_WIDE_DASHED),
     112, uint(muse::ui::IconCode::Code::ZOOM_TOGGLE),
     113, uint(muse::ui::IconCode::Code::FIT_SELECTION),
     114, uint(muse::ui::IconCode::Code::FIT_PROJECT),
     115, uint(muse::ui::IconCode::Code::TRIM_AUDIO_OUTSIDE_SELECTION),
     116, uint(muse::ui::IconCode::Code::SILENCE_AUDIO_SELECTION),
     117, uint(muse::ui::IconCode::Code::LINE_DOTTED),
     118, uint(muse::ui::IconCode::Code::LINE_NORMAL),
     119, uint(muse::ui::IconCode::Code::LINE_WITH_END_HOOK),
     120, uint(muse::ui::IconCode::Code::LINE_WITH_ANGLED_END_HOOK),
     121, uint(muse::ui::IconCode::Code::LINE_PEDAL_STAR_ENDING),
     122, uint(muse::ui::IconCode::Code::BEAM_FEATHERED_ACCELERATE),
     123, uint(muse::ui::IconCode::Code::BEAM_FEATHERED_DECELERATE),
     124, uint(muse::ui::IconCode::Code::RIGHT_GAP),
     125, uint(muse::ui::IconCode::Code::LEFT_GAP),
     126, uint(muse::ui::IconCode::Code::GAP_BELOW),
     127, uint(muse::ui::IconCode::Code::GAP_ABOVE),
     128, uint(muse::ui::IconCode::Code::LEFT_MARGIN),
     129, uint(muse::ui::IconCode::Code::RIGHT_MARGIN),
     130, uint(muse::ui::IconCode::Code::BOTTOM_MARGIN),
     131, uint(muse::ui::IconCode::Code::TOP_MARGIN),
     132, uint(muse::ui::IconCode::Code::MIDI_INPUT),
     133, uint(muse::ui::IconCode::Code::ACCOUNT),
     134, uint(muse::ui::IconCode::Code::STAR),
     135, uint(muse::ui::IconCode::Code::LINE_WITH_TWO_INVERTED_HOOKS),
     136, uint(muse::ui::IconCode::Code::LINE_WITH_T_LIKE_END_HOOK),
     137, uint(muse::ui::IconCode::Code::LINE_WITH_T_LINE_START_HOOK),
     138, uint(muse::ui::IconCode::Code::LINE_WITH_START_HOOK),
     139, uint(muse::ui::IconCode::Code::LINE_WITH_ANGLED_START_HOOK),
     140, uint(muse::ui::IconCode::Code::LINE_WITH_INVERTED_START_HOOK),
     141, uint(muse::ui::IconCode::Code::IMAGE_MOUNTAINS),
     142, uint(muse::ui::IconCode::Code::GRADUATION_CAP),
     143, uint(muse::ui::IconCode::Code::SCORE),
     144, uint(muse::ui::IconCode::Code::CLEF_TREBLE),
     145, uint(muse::ui::IconCode::Code::AUTO_TEXT),
     146, uint(muse::ui::IconCode::Code::BEAM_NONE),
     147, uint(muse::ui::IconCode::Code::BEAM_BREAK_LEFT),
     148, uint(muse::ui::IconCode::Code::BEAM_JOIN),
     149, uint(muse::ui::IconCode::Code::BEAM_BREAK_INNER_8TH),
     150, uint(muse::ui::IconCode::Code::BEAM_BREAK_INNER_16TH),
     151, uint(muse::ui::IconCode::Code::QUESTION_MARK),
     152, uint(muse::ui::IconCode::Code::NOTE_HEAD_QUARTER),
     153, uint(muse::ui::IconCode::Code::NOTE_HEAD_HALF),
     154, uint(muse::ui::IconCode::Code::NOTE_HEAD_WHOLE),
     155, uint(muse::ui::IconCode::Code::NOTE_HEAD_BREVIS),
     156, uint(muse::ui::IconCode::Code::NOTE_HEAD),
     157, uint(muse::ui::IconCode::Code::NOTE_HEAD_PARENTHESES),
     158, uint(muse::ui::IconCode::Code::PLAY_REPEATS),
     159, uint(muse::ui::IconCode::Code::BARLINE_WINGED),
     160, uint(muse::ui::IconCode::Code::BARLINE_UNWINGED),
     161, uint(muse::ui::IconCode::Code::ORIENTATION_PORTRAIT),
     162, uint(muse::ui::IconCode::Code::ORIENTATION_LANDSCAPE),
     163, uint(muse::ui::IconCode::Code::CHORD_SYMBOL),
     164, uint(muse::ui::IconCode::Code::GUITAR_BEND),
     165, uint(muse::ui::IconCode::Code::MULTIMEASURE_REST),
     166, uint(muse::ui::IconCode::Code::IMPORT),
     167, uint(muse::ui::IconCode::Code::UPDATE),
     168, uint(muse::ui::IconCode::Code::OPEN_LINK),
     169, uint(muse::ui::IconCode::Code::GUITAR_TREMOLO_BAR),
     170, uint(muse::ui::IconCode::Code::SHORTCUTS),
     171, uint(muse::ui::IconCode::Code::TREMOLO_TWO_NOTES),
     172, uint(muse::ui::IconCode::Code::TREMOLO_STYLE_DEFAULT),
     173, uint(muse::ui::IconCode::Code::TREMOLO_STYLE_TRADITIONAL),
     174, uint(muse::ui::IconCode::Code::TREMOLO_ONE_NOTE),
     175, uint(muse::ui::IconCode::Code::TREMOLO_STYLE_TRADITIONAL_ALTERNATE),
     176, uint(muse::ui::IconCode::Code::LONGO),
     177, uint(muse::ui::IconCode::Code::NOTE_WHOLE_DOUBLE),
     178, uint(muse::ui::IconCode::Code::NOTE_WHOLE),
     179, uint(muse::ui::IconCode::Code::NOTE_HALF),
     180, uint(muse::ui::IconCode::Code::NOTE_QUARTER),
     181, uint(muse::ui::IconCode::Code::NOTE_8TH),
     182, uint(muse::ui::IconCode::Code::NOTE_16TH),
     183, uint(muse::ui::IconCode::Code::NOTE_32ND),
     184, uint(muse::ui::IconCode::Code::NOTE_64TH),
     185, uint(muse::ui::IconCode::Code::NOTE_128TH),
     186, uint(muse::ui::IconCode::Code::NOTE_256TH),
     187, uint(muse::ui::IconCode::Code::NOTE_512TH),
     188, uint(muse::ui::IconCode::Code::NOTE_1024TH),
     189, uint(muse::ui::IconCode::Code::REST),
     190, uint(muse::ui::IconCode::Code::NOTE_DOTTED),
     191, uint(muse::ui::IconCode::Code::NOTE_TIE),
     192, uint(muse::ui::IconCode::Code::NOTE_FLIP),
     193, uint(muse::ui::IconCode::Code::NOTE_SLUR),
     194, uint(muse::ui::IconCode::Code::NOTE_TUPLET),
     195, uint(muse::ui::IconCode::Code::KEY_SIGNATURE_NONE),
     196, uint(muse::ui::IconCode::Code::KEY_SIGNATURE_1_SHARP),
     197, uint(muse::ui::IconCode::Code::KEY_SIGNATURE_2_SHARPS),
     198, uint(muse::ui::IconCode::Code::KEY_SIGNATURE_3_SHARPS),
     199, uint(muse::ui::IconCode::Code::KEY_SIGNATURE_4_SHARPS),
     200, uint(muse::ui::IconCode::Code::KEY_SIGNATURE_5_SHARPS),
     201, uint(muse::ui::IconCode::Code::KEY_SIGNATURE_6_SHARPS),
     202, uint(muse::ui::IconCode::Code::KEY_SIGNATURE_7_SHARPS),
     203, uint(muse::ui::IconCode::Code::KEY_SIGNATURE_1_FLAT),
     204, uint(muse::ui::IconCode::Code::KEY_SIGNATURE_2_FLAT),
     205, uint(muse::ui::IconCode::Code::KEY_SIGNATURE_3_FLAT),
     206, uint(muse::ui::IconCode::Code::KEY_SIGNATURE_4_FLAT),
     207, uint(muse::ui::IconCode::Code::KEY_SIGNATURE_5_FLAT),
     208, uint(muse::ui::IconCode::Code::KEY_SIGNATURE_6_FLAT),
     209, uint(muse::ui::IconCode::Code::KEY_SIGNATURE_7_FLAT),
     210, uint(muse::ui::IconCode::Code::SHARP),
     211, uint(muse::ui::IconCode::Code::NATURAL),
     212, uint(muse::ui::IconCode::Code::FLAT),
     213, uint(muse::ui::IconCode::Code::FLAT_DOUBLE),
     214, uint(muse::ui::IconCode::Code::SHARP_DOUBLE),
     215, uint(muse::ui::IconCode::Code::MARCATO),
     216, uint(muse::ui::IconCode::Code::ACCENT),
     217, uint(muse::ui::IconCode::Code::TENUTO),
     218, uint(muse::ui::IconCode::Code::STACCATO),
     219, uint(muse::ui::IconCode::Code::BYPASS),
     220, uint(muse::ui::IconCode::Code::VOICE_1),
     221, uint(muse::ui::IconCode::Code::VOICE_2),
     222, uint(muse::ui::IconCode::Code::VOICE_3),
     223, uint(muse::ui::IconCode::Code::VOICE_4),
     224, uint(muse::ui::IconCode::Code::NOTE_DOTTED_2),
     225, uint(muse::ui::IconCode::Code::NOTE_DOTTED_3),
     226, uint(muse::ui::IconCode::Code::NOTE_DOTTED_4),
     227, uint(muse::ui::IconCode::Code::COPY),
     228, uint(muse::ui::IconCode::Code::PASTE),
     229, uint(muse::ui::IconCode::Code::CUT),
     230, uint(muse::ui::IconCode::Code::CHEVRON_RIGHT),
     231, uint(muse::ui::IconCode::Code::CHEVRON_LEFT),
     232, uint(muse::ui::IconCode::Code::NOTE_PLUS),
     233, uint(muse::ui::IconCode::Code::NOTE_TO_RIGHT),
     234, uint(muse::ui::IconCode::Code::RHYTHM_ONLY),
     235, uint(muse::ui::IconCode::Code::RE_PITCH),
     236, uint(muse::ui::IconCode::Code::FOOT_PEDAL),
     237, uint(muse::ui::IconCode::Code::TOOLBAR_GRIP),
     238, uint(muse::ui::IconCode::Code::GRID),
     239, uint(muse::ui::IconCode::Code::PAGE),
     240, uint(muse::ui::IconCode::Code::LIST),
     241, uint(muse::ui::IconCode::Code::CAMERA),
     242, uint(muse::ui::IconCode::Code::CONTINUOUS_VIEW_VERTICAL),
     243, uint(muse::ui::IconCode::Code::PAN_SCORE),
     244, uint(muse::ui::IconCode::Code::COUNT_IN),
     245, uint(muse::ui::IconCode::Code::GLOBE),
     246, uint(muse::ui::IconCode::Code::PRINT),
     247, uint(muse::ui::IconCode::Code::DOWN),
     248, uint(muse::ui::IconCode::Code::UP),
     249, uint(muse::ui::IconCode::Code::LOOP_IN),
     250, uint(muse::ui::IconCode::Code::LOOP_OUT),
     251, uint(muse::ui::IconCode::Code::PAUSE),
     252, uint(muse::ui::IconCode::Code::WARNING),
     253, uint(muse::ui::IconCode::Code::INFO),
     254, uint(muse::ui::IconCode::Code::ERROR),
     255, uint(muse::ui::IconCode::Code::QUESTION),
     256, uint(muse::ui::IconCode::Code::MUTE),
     257, uint(muse::ui::IconCode::Code::SOLO),
     258, uint(muse::ui::IconCode::Code::OTTAVA),
     259, uint(muse::ui::IconCode::Code::PALM_MUTE),
     260, uint(muse::ui::IconCode::Code::LET_RING),
     261, uint(muse::ui::IconCode::Code::VOLTA),
     262, uint(muse::ui::IconCode::Code::VIBRATO),
     263, uint(muse::ui::IconCode::Code::DIMINUENDO),
     264, uint(muse::ui::IconCode::Code::CRESCENDO),
     265, uint(muse::ui::IconCode::Code::MICROPHONE),
     266, uint(muse::ui::IconCode::Code::APP_MINIMIZE),
     267, uint(muse::ui::IconCode::Code::APP_MAXIMIZE),
     268, uint(muse::ui::IconCode::Code::APP_UNMAXIMIZE),
     269, uint(muse::ui::IconCode::Code::APP_CLOSE),
     270, uint(muse::ui::IconCode::Code::NOTEFLAGS_TRADITIONAL),
     271, uint(muse::ui::IconCode::Code::NOTEFLAGS_STRAIGHT),
     272, uint(muse::ui::IconCode::Code::TUPLET_NUMBER_WITH_BRACKETS),
     273, uint(muse::ui::IconCode::Code::TUPLET_NUMBER_ONLY),
     274, uint(muse::ui::IconCode::Code::USE_WIDE_BEAMS_REGULAR),
     275, uint(muse::ui::IconCode::Code::USE_WIDE_BEAMS_WIDE),
     276, uint(muse::ui::IconCode::Code::ACCIACCATURA),
     277, uint(muse::ui::IconCode::Code::APPOGGIATURA),
     278, uint(muse::ui::IconCode::Code::GRACE4),
     279, uint(muse::ui::IconCode::Code::GRACE16),
     280, uint(muse::ui::IconCode::Code::GRACE32),
     281, uint(muse::ui::IconCode::Code::GRACE8_AFTER),
     282, uint(muse::ui::IconCode::Code::GRACE16_AFTER),
     283, uint(muse::ui::IconCode::Code::GRACE32_AFTER),
     284, uint(muse::ui::IconCode::Code::MEASURE_REPEAT),
     285, uint(muse::ui::IconCode::Code::INSERT_ONE_MEASURE),
     286, uint(muse::ui::IconCode::Code::STAFF_TYPE_CHANGE),
     287, uint(muse::ui::IconCode::Code::CLOUD),
     288, uint(muse::ui::IconCode::Code::WAVEFORM),
     289, uint(muse::ui::IconCode::Code::CROSS_STAFF_BEAMING),
     290, uint(muse::ui::IconCode::Code::TEMPO_CHANGE),
     291, uint(muse::ui::IconCode::Code::PLUGIN),
     292, uint(muse::ui::IconCode::Code::LYRICS),
     293, uint(muse::ui::IconCode::Code::LEARN),
     294, uint(muse::ui::IconCode::Code::SPECTROGRAM),
     295, uint(muse::ui::IconCode::Code::SPECTROGRAM_BOX_SELECTION),
     296, uint(muse::ui::IconCode::Code::BRUSH),
     297, uint(muse::ui::IconCode::Code::PLAY_FILL),
     298, uint(muse::ui::IconCode::Code::STOP_FILL),
     299, uint(muse::ui::IconCode::Code::REWIND_START_FILL),
     300, uint(muse::ui::IconCode::Code::REWIND_END_FILL),
     301, uint(muse::ui::IconCode::Code::RECORD_FILL),
     302, uint(muse::ui::IconCode::Code::PAUSE_FILL),
     303, uint(muse::ui::IconCode::Code::REST_8TH),
     304, uint(muse::ui::IconCode::Code::CIRCLE),
     305, uint(muse::ui::IconCode::Code::SHARE_AUDIO),
     306, uint(muse::ui::IconCode::Code::DYNAMIC_CENTER_1),
     307, uint(muse::ui::IconCode::Code::DYNAMIC_CENTER_2),
     308, uint(muse::ui::IconCode::Code::EXPRESSION),
     309, uint(muse::ui::IconCode::Code::CLOUD_FILL),
     310, uint(muse::ui::IconCode::Code::BRAILLE),
     311, uint(muse::ui::IconCode::Code::AUTOMATION),
     312, uint(muse::ui::IconCode::Code::GUITAR_BEND_REGULAR),
     313, uint(muse::ui::IconCode::Code::GUITAR_PRE_BEND),
     314, uint(muse::ui::IconCode::Code::GUITAR_GRACE_NOTE_BEND),
     315, uint(muse::ui::IconCode::Code::GUITAR_SLIGHT_BEND),
     316, uint(muse::ui::IconCode::Code::GUITAR_BEND_STYLE_1),
     317, uint(muse::ui::IconCode::Code::GUITAR_BEND_STYLE_FULL),
     318, uint(muse::ui::IconCode::Code::TIE_OUTSIDE),
     319, uint(muse::ui::IconCode::Code::TIE_INSIDE),
     320, uint(muse::ui::IconCode::Code::TIE_CHORD_OUTSIDE),
     321, uint(muse::ui::IconCode::Code::TIE_CHORD_INSIDE),
     322, uint(muse::ui::IconCode::Code::TRIANGLE_SYMBOL),
     323, uint(muse::ui::IconCode::Code::NONE),

       0        // eod
};

Q_CONSTINIT const QMetaObject muse::ui::IconCode::staticMetaObject = { {
    nullptr,
    qt_meta_stringdata_CLASSmuseSCOPEuiSCOPEIconCodeENDCLASS.offsetsAndSizes,
    qt_meta_data_CLASSmuseSCOPEuiSCOPEIconCodeENDCLASS,
    nullptr,
    nullptr,
    qt_incomplete_metaTypeArray<qt_meta_stringdata_CLASSmuseSCOPEuiSCOPEIconCodeENDCLASS_t,
        // enum 'Code'
        QtPrivate::TypeAndForceComplete<IconCode::Code, std::true_type>,
        // Q_OBJECT / Q_GADGET
        QtPrivate::TypeAndForceComplete<IconCode, std::true_type>
    >,
    nullptr
} };

QT_WARNING_POP
