// This file is autogenerated. Changes will be overwritten.
#include "M6NRSKQBH3/moc_macosshortcutsinstancemodel.cpp"
#include "EGDWYGFDBT/moc_shortcutsinstancemodel.cpp"
#include "OTUN7GXZT4/moc_editmidimappingmodel.cpp"
#include "OTUN7GXZT4/moc_editshortcutmodel.cpp"
#include "OTUN7GXZT4/moc_mididevicemappingmodel.cpp"
#include "OTUN7GXZT4/moc_shortcutsmodel.cpp"
